### ISSUE TITLE
loading account from oidc-provider session

### ISSUE THREAD

**Issue by jessereitsma** [panva/node-oidc-provider#110]
Hello,

I want to be able to show the users email on the interaction screen (interaction.ejs, the one with the continue button)
But the email is not located in the details object.
I've tried to debug some, but can't really find where that object is generated. And where I can add email to that cookie / details object.

**Comment by panva** [comment]
The provider does not create any object for interactions with the account claims, this goes beyond what the library intends to provide.

Why don't you apply what you would do with any other "logged in" state page - get session id from cookie, load session, read account id, load account, display claims.

**Comment by jessereitsma** [comment]
The only things I got are `uuid` and `params.state`.
And I don't know how to resolve that to a cookie / (redis-)session containing the email.

Or is that not provided / implemented at all?
That I have to create my own redis-session containing the email, combined with a token that I set as a cookie?

**Comment by panva** [comment]
> And I don't know how to resolve that to a cookie / (redis-)session containing the email.
> 
> Or is that not provided / implemented at all?
That I have to create my own redis-session containing the email, combined with a token that I set as a cookie?

I'm sorry, this makes little sense to me.

This library does NOT provide the account connection, the interactions or the adapters to your session, none if it, you do so. And you're expected to know how to read a cookie and load an entity from your own persistence layer using an identifier after you've implemented these adapters. Maybe you're looking for an out of the box solution instead of `oidc-provider` which is only meant to provide the tools for you to build openid connect interfaces.

**Comment by jessereitsma** [comment]
Ok, I will take a look.
Thanks for your quick replies.
