### ISSUE TITLE
How to return a scope like user:read 

### ISSUE THREAD

**Issue by JayChandler** [panva/node-oidc-provider#128]
Hello

How can i return a scope like `user:read` that basically has no value and is just a boolean flag. Dont' t want this claim to have a value an be in the id token. It should just just appear in the response scope value ?

**Comment by panva** [comment]
> It should just just appear in the response scope value ?

I've got literally 0 idea as to what you mean.

**Comment by JayChandler** [comment]
Okay :/ 

My provider has a custom scope called `user:read`. I have looked in the example folder and there is a `claims()` method in the Account class which basically does this.

```
claims() {
    return {
      address: {
        country: '000',
        formatted: '000',
        locality: '000',
        postal_code: '000',
        region: '000',
        street_address: '000',
      },
      birthdate: '1987-10-16',
      email: 'johndoe@example.com',
      email_verified: false,
      family_name: 'Doe',
      gender: 'male',
      given_name: 'John',
      locale: 'en-US',
      middle_name: 'Middle',
      name: 'John Doe',
      nickname: 'Johny',
      phone_number: '+49 000 000000',
      phone_number_verified: false,
      picture: 'http://lorempixel.com/400/200/',
      preferred_username: 'Jdawg',
      profile: 'https://johnswebsite.com',
      sub: this.accountId,
      updated_at: 1454704946,
      website: 'http://example.com',
      zoneinfo: 'Europe/Berlin',
    };
  }

```

This returns a key value object. I dont't know how i have to return my value `user:read` because it simply has no value. Hope this makes it clearer. Thx

**Comment by panva** [comment]
> Hope this makes it clearer. Thx

No not really. What do you wish to have returned from where? If at all possible - use OpenID Connect terminology.

**Comment by JayChandler** [comment]
Okay then please explain me at which point in the code the claims for the user get returned. I just want to have a scope `user:read` and return it to the client. I want to know how i can do that.

**Comment by panva** [comment]
Believe it or not, the `claims` method is used to customize the claims returned to clients in id tokens and userinfo responses.

**Comment by JayChandler** [comment]
> You should return all claims available, and the provider will cherry pick the ones requested by the request scopes.

Right and how do i return a value like `user:read` which is a boolean flag ?

```
return {
  'user:read' : null ?
}
```

Does the value of  `user:read` appear in the id token `?

**Comment by panva** [comment]
Yes, the provider will cherry pick the individual claims requested by the request scopes. A mapping of scopes to claims is done by configuring your provider. Please see the configuration section of oidc-provider.

**Comment by slavab89** [comment]
If i understood correctly what you want, i'm not 100% you need claims. It might be enought for you to use scopes (Though i always confuse myself on what claims are for and what scopes are for).

As part of the initialization you are able to define the list of scopes that you want your provider to support, using the `scopes` field naturally. There you can put the `user:read` scope and it will be part of the issued tokens (as one of the fields in the introspected token).

@panva please correct me on the general differences between claims and scopes

scope: Present on the token itself, used to define "things" that the token or whoever holds it can do
claims: Defines what info can you get from the account based on the scope.
This means that in order to get scopes, you have to make an `introspect token` request and in order to get claims you have to make a `userinfo` request

**Comment by panva** [comment]
@slavab89 well that's one way to put it, but @JayChandler also wants a claim "user:read" to be returned in the id token.

TBH i would just use a custom scope and do an access token introspection, like @slavab89 pointed out.

**Comment by JayChandler** [comment]
@panva may i ask you some questions about client_credentials flow via mail ?

**Comment by panva** [comment]
sure.
