### ISSUE TITLE
Authorization / interaction workflow

### ISSUE THREAD

**Issue by maitscha** [panva/node-oidc-provider#138]
Hi!

I'm trying to understand how the interaction works, how the redirects between the authorization/ interaction/resume handlers work, which cookies are used and what sessions are stored.

As far as I can see, the provider checks if an interaction is required (`authorization/interaction.js`), and if so, it makes a redirect to the interaction URL (for example `/grant/<grant-uuid>`). 2 cookies are stored (`_session` and `_grant`) to store the uuid of the authenticated session and the interaction session. When the interaction has been finished (calling `interactionFinished`), a redirect is made to the `/resume/<grant-uuid>` endpoint, which itself redirects to the redirect URI of the authorization call (which is stored in the interaction session).

* Why is it necessary to use a cookie for the uuid of the interaction session? The interaction session uuid is always provided as URL path parameter in the interaction and resume URL.
* Do you have a flow chart or anything similar which describes the authorization flow?
* Where is the long living session created, and why does it contain a `authorizations` array containing a reference to the client id?
* Why are so many redirects used, or is this a requirement of the OpenID Connect spec?

Thank you for your clarifications!

Cheers

**Comment by panva** [comment]
"^1.0.0" or "^2.0.0" semver range?

**Comment by maitscha** [comment]
`^2.0.0`

**Comment by panva** [comment]
> Why is it necessary to use a cookie for the uuid of the interaction session? The interaction session uuid is always provided as URL path parameter in the interaction and resume URL.

In general oidc-provider stores these references in the cookie so that they are bound to the User-Agent.

> Do you have a flow chart or anything similar which describes the authorization flow?

Authorization Flow itself is described in Core 1.0. Flow chart for the oidc-provider requesting interactions - no.

> Where is the long living session created, and why does it contain a `authorizations` array containing a reference to the client id?

The long-lived session gets created with a successful authorization in the `lib/shared/session.js` middleware. It contains `authorizations` to support Session Management 1.0 as well as a default "client not authorized in this session yet" interaction (see the default `interactionCheck` implementation)

> Why are so many redirects used, or is this a requirement of the OpenID Connect spec?

- client to authorization endpoint (spec)
- authorization endpoint to interaction (implementation)
- interaction back to authorization endpoint to resume (necessity, implementation)
- authorization endpoint to client (spec)

The idea here is that the library does NOT care how and what the interaction does, if you provide a login form, consent form or whatever - it does not matter to the lib, it should to you, but not the lib. The lib will take care of proper openid connect behaviors and that's it. And to hand-off the request to either another route you define or even another application, that's just how i chose to approach having to have this flexible. The interaction app gets details about the request so that it can resolve the interaction that's needed.
