### ISSUE TITLE
Add "Resource Owner Password Credentials Grant"

### ISSUE THREAD

**Issue by schlosbo** [panva/node-oidc-provider#14]
As you already added "Client Credentials Grant" you should also add the "Resource Owner Password Credentials Grant" as stated in RFC 6749: https://tools.ietf.org/html/rfc6749#section-4.3

**Comment by panva** [comment]
Should be rather easy, i'm struggling to finalize the "Account" model configuration and API, once that's stable this is a breeze. This feature can however become very opinionated, i would appreciate more input on how you'd like oidc-provider to handle this grant. i.e. does the grant issue an id_token, access_token and a refresh_token? If not, why, and so on.

**Comment by schlosbo** [comment]
I would pretty much stick with the OAuth RFC. This means the grant issues an access_token and an optional refresh_token. As the grant is no part of the OIDC spec I would not issue an id_token. Also in my opinion only high trusted apps should be able to use this grant. These apps mostly already have much information about the user so the id_token is not mandatory.

**Comment by panva** [comment]
in [o-eight](https://github.com/panva/node-oidc-provider/tree/o-eight#custom-grant-types) it's possible to extend the available grants, i chose this route since i want to keep the must-have interface for the user/account model the minimum, "generic" enough grants will always be part of the library, resource owner password ain't one of them. With the example linked do you think you have enough at hand to implement your grant?

**Comment by schlosbo** [comment]
I really like your approach. I have already tested it and it is working like a charm. Thank you!
