### ISSUE TITLE
upsert  data to the current adapter in provider

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#141]
From the example, is there any way Account can detect the adapter set in provider configuration and upsert an account information to the adapter storage? Thanks.

**Comment by panva** [comment]
There is no place in the library which would use the adapter for Account data. Accounts are only looked up using the `findById` helper.

**Comment by mogeda** [comment]
I was wondering whether there is a way I can detect adpdater information from provider. Any advise on this please?

**Comment by panva** [comment]
Would love to help but I don't get the request.

**Comment by mogeda** [comment]
I see oidc-provider gets an adapter by calling like below.
	new (provider.configuration('adapter'))(collection_name);

I would like to put some data to new collection then need to get an adapter first, right?

**Comment by panva** [comment]
Still no comprende. Give me an example of what you want when to happen.

**Comment by mogeda** [comment]
I'm using/learning the example in oidc-provider module with default configuration, FYI.

I'm trying to figure out how to add an extra collection to the current adapter which provider is using.
Let's say I'd like to put some predefined admin accounts to 'admin' collection. I simply tried to create a collection 'admin' like below after provider initialized, i.e after validating provider.initialized true.
if(provider.initialized) {
	const adapter = provider.configuration('adapter');
	// TODO create collection after get adpater information
}
It looks it's not supported so it threw an error. I checked provider.js too but wasn't able to figure out how to retrieve adapter information. Please advise what's the right way to handle this. 
Thanks a lot.

**Comment by panva** [comment]
don't see the need to return the adapter from the provider instance, since you provide it's constructor in -
 what you're trying to do is overly complicated.

1) in ^2.0.0 there's an adapter class method `connect` called to help with init phases
2) you're in javascript - your adapter js file may also collect the instances in the constructor to an object you make yourself available
3) Adapter is not used for accounts, its used for OIDC token entities and sessions but not accounts.
