### ISSUE TITLE
client_credentials flow not consistent (^1.0.0)

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#142]
I'm still using version 1 (will upgrade soon to version 2) but in the meantime, i'm trying to get client_credentials flow to work and i'm seeing a weird behavior.
I've defined a client with the following values:
```js
{
    "client_secret" : "XXXXXX",
    "client_id" : "YYYY",
    "redirect_uris" : [ "http://localhost:5000" ],
    "grant_types" : [ "client_credentials" ],
}
```
I'm making a client credentials request:
```
curl -X POST http://localhost:8000/op/token -H 'authorization: Basic ZZZ -H 'content-type: application/x-www-form-urlencoded' -d grant_type=client_credentials
```
And i get the following error
```
{
    "error": "invalid_client_metadata",
    "error_description": "grant_types must contain authorization_code when code is amongst response_types"
}
```
Do i have to include authorization_code as a grant?

In any case, i did add the authorization_code as a grant and then was able to get the token back.
Then the strange thing: I removed the authorization_code grant from the client object in the DB and tried to get another token - This request still went though and i got the token (There was no authorization_code grant anymore in the DB client object).

If i then restart the server, i go back to receiving the error about a missing authorization_code grant. Its like the client is cached or something?

**edit:**
I understand that i can just put a empty array of `response_types` and it will work, but the original issue is still happening to me (If i use the default `response_types` which is `code`)

**Comment by panva** [comment]
1) yes clients are always cached, and are loaded the first time they are needed, hence, since your config is invalid when you do the call it the client instance validation will fail and throw to the context see https://github.com/panva/node-oidc-provider/blob/v1.x/docs/configuration.md#clients
1) for client credential ONLY clients do this, the reason is response_types is populated for you with the default value `["code"]`, hence it looks for auth_code grant type, hope it's understandable.

```
{
  client_id: 'resource-server',
  client_secret: 'foobar',
  redirect_uris: [],
  response_types: [],
  grant_types: ['client_credentials']
}
```

**Comment by slavab89** [comment]
As usual, a simple explanation =]
