### ISSUE TITLE
adapter backed clients - control cache TTL

### ISSUE THREAD

**Issue by panva** [panva/node-oidc-provider#143]
It should be possible to tell oidc-provider for how long a client should be kept in cache before it's loaded from the adapter again. Default is forever.

options
- ~property in the returned client object (a {Number} property - seconds)~
- static configuration (default forever, can be set to {Number} of seconds)
- ~when both are present the client object property takes over.~

edit: descoped

**Comment by slavab89** [comment]
There is also an option to clear all clients in cache at once using `provider.Client.cacheClear()` as i understand. Would it be possible, as part of this enhancement, provide the ability to invalidate only 1 client?

In case i write some admin console for the OP and want to edit some parameters of the clients, the client would either "refresh" if the TTL passes or a "hard invalidate" is performed.

**Comment by panva** [comment]
> In case i write some admin console for the OP and want to edit some parameters of the clients, the client would either "refresh" if the TTL passes or a "hard invalidate" is performed.

A console would be a separate process, wouldn't it? Furthermore I don't get what you mean by refresh or hard invalidation. A client will continue to be loaded when required, the difference is that clients will be continuously removed from the cache.

**Comment by slavab89** [comment]
Yes it would be a separate process.
They will be removed from the cache based on the **TTL** that you want to add now.
I was asking for an option to force a removal of a client from the cache. Today it seems that you've created an option to clear the whole cache using `provider.Client.cacheClear()` but i was asking about the ability to remove only 1.

Example:
Dont have a TTL defined. If i edit some client i would need to clear the whole cache of clients using `provider.Client.cacheClear()` rather than only the one i've edited.
In case i do have a TTL defined then i might still want to remove the client from the cache and reload before the TTL passes.

**Comment by panva** [comment]
> Today it seems that you've created an option to clear the whole cache

`cacheClear()` is there and documented since ^1.8.0 (at least according to the changelog)

>  but i was asking about the ability to remove only 1

This is not there, can you open a PR?

**Comment by slavab89** [comment]
Sure thing.

**Comment by codestorycooked** [comment]
@panva  @slavab89  Is it possible to delete the only client which is edited from cache? If YES where can I do it programmatically?

Thanks a much

**Comment by panva** [comment]
@codestorycooked it is not.
