### ISSUE TITLE
additional metadata for client

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#175]
There is a comment, 'Additional Client Metadata parameters MAY also be used' in http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata so I wonder whether there is any way to add extra metadata for client registration. It looks registration payload filtered by RECOGNIZED_METADATA in client_schema.js.

**Comment by panva** [comment]
Hi @mogeda, there is no support for extending the recognized client metadata. What use would you have for these?

**Comment by mogeda** [comment]
trying to add scope for client

**Comment by panva** [comment]
Still don’t see how it would be picked up and used by the existing functionality.

**Comment by panva** [comment]
What i can do for the next release (since it does actually touch client metadata and restructures alot) is to put all consts from client schema to a separate js file, this will allow you to require this file from within your app and change them, i.e. add 'scope' and make sure it's validated as a string.

**Comment by mogeda** [comment]
I was referring to https://tools.ietf.org/html/rfc7591#section-2 though it's for oauth2 rather than openid, will check the branch you pointed. Thanks a lot.

**Comment by panva** [comment]
Specifications usually read this way to support extensions, in your case there's none, but the update will allow you to diverge from the specs and set this up.
