### ISSUE TITLE
Security Measures

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#192]
Hi @panva,

Does this library carry out all the best practices for Threat Analysis mentioned in https://tools.ietf.org/html/rfc6819? Are there any security holes which as a consumer of the library I need to handle? 

Thanks for you help.

**Comment by panva** [comment]
Hi @codestorycooked,

- Threats related to TLS (mostly eavesdropping) are to be covered by your deployment. I.e. TLS offloading proxy which enforces https only access.
- Threats related to User Interactions are to be covered by your own Interaction implementations, since oidc-provider comes with none.
- Threats related to RPs (e.g. leaking tokens), no TODO on OP
- Token revocation upon detected consumed token/code use is supported through your own adapter or emitted events
- Refresh Token rotation is enabled by default
- standard header setup should be handled by your app through the use of https://github.com/helmetjs/helmet, oidc-provider does not push these in

If you have specific questions about some of the RFC6819 points feel free to ask.
