### ISSUE TITLE
Re-use an existing session

### ISSUE THREAD

**Issue by marcortw** [panva/node-oidc-provider#245]
I implemented a working authorization code flow between my RP and my OP. The is OP based on your step-by-step node-oidc-provider-example, using express and ejs; session management is enabled. The RP is implemented with node-openid-client. I understand that my RP chooses a random state parameter in the redirect to the OP, and the OP then internally creates a random interaction ID/grant and redirects the browser to the "interaction url". After I have authenticated the user, with a call to `interactionFinished`, the browser gets redirected to `/auth/:grant` and gets his cookies. From what I observe, the `_session ` is then cached and flagged as authenticated on the OP (or mapped to the grant or I-don't-know-what-magic-happens).

I'd like to implement a very simple profile page, preferably residing on the OP on a separate `/profile` url (without a grant or something else in the URL), just to display some of his attributes. Is it possible to use/access the OP's (possibly) already existing valid session instead of implementing my own session management? Or should something like this be done with a separate 'user management' client?

To start with something like this doesn't work, I get an error `id must be provided to Session#find`

```
expressApp.get('/profile', parse, async (req, res, next) => {
        const details = await oidc.interactionDetails(req);
        console.log('request to ' + req.originalUrl + ' in state: ' + details.interaction.reason);
    });
```
Kind regards,
Marco

**Comment by panva** [comment]
You can use the OP session just fine, it is after all

- stored using your own adapter on the backend
- referenced by a cookie in the user-agent

If you're running in the same app/process as your provider instance and running koa this is very easy.

```js
const session = await provider.Session.get(ctx);
```

Since you're running express you must retrieve the session cookie value yourself (hopefully your provider is using keys to sign the cookies, so you'll have to use keygrip or https://github.com/pillarjs/cookies with the same keys to do it for you) and simply

```js
const session = await provider.Session.find(sessionIdFromCookie);
```

or, using the ctx the internals expect even from express

```js
const ctx = provider.app.createContext(req, res);
const session = await provider.Session.get(ctx);
```

Alternatively you can use any mechanism you can think of and deem secure and load the session data from your adapter.

> To start with something like this doesn't work, I get an error

Of course it doesn't it's looking for an interaction session, not an OP session :)

**Comment by marcortw** [comment]
Thanks a lot for your quick response which pointed me in the right direction! Out of curiosity: There's no library-provided way to start an OP session other than going through an interaction session?

**Comment by panva** [comment]
There is not, but once you get familiar with the format, you'll sure manage.
