### ISSUE TITLE
Hooks for redirectUri verification

### ISSUE THREAD

**Issue by debben** [panva/node-oidc-provider#249]
Would it be possible provide a callback or other hook to allow for alternative verification of redirectUri? Right now I have an RP accessible via multiple host names that follow a pattern. For example `<tenant_prefix>.myawesomeapp.io`. I have a list of tenants that will that each access the service using their prefix. I'm trying to support this in the redirect_uris metadata property of a client for this RP. 

I've attempted to build a client adapter that reads from a table of these tenant specific URLs and applies them to the redirect_uris property before returning the client metadata. There are two issues with this approach however:

- The node-oidc-provider caches the client metadata my adapter returns. Any changes to my list of tenants will not be reflected in the cached client metadata. I can get around this by setting `clientCacheDuration` to nothing and implementing a cache of my own in the adapter.
- These URLs always will follow the same pattern. I'd rather not have to maintain a table of these host names every time a tenant is added or removed. My primary concern is how this will scale.

Would it be possible to get some way of overriding the redirectUriAllowed method of client.js with behavior provided by the library consumer at the time the library is configured?

**Comment by panva** [comment]
Supporting wildcards is not on my list of todo since it does open up a number of attacks on OAuth2.0 providers and is very simply put a bad practice, there's nothing wrong with invalidating your client cache (through supported API), or clearing a single one (through supported API) and expand the list of used redirect_uris on demand.

> I can get around this by setting clientCacheDuration to nothing and implementing a cache of my own in the adapter.

Setting `clientCacheDuration` to nothing (0, undefined, false) will pass this to node-lru-cache and it will be cached indefinitely or until the cache runs out of alocated space.

> Would it be possible to get some way of overriding the redirectUriAllowed method of client.js

You can do this already today with any method on a client prototype or its constructor as well as other models, although not officially, subject to API changes, `provider.Client.prototype.redirectUriAllowed` is accessible to you, redefine at your own risk, it is not marked as a public method.

**Comment by panva** [comment]
Out of curiosity, is this work you’re doing for plex?

**Comment by debben** [comment]
Thanks @panva for the quick response. I'm not a fan of supporting wildcards either. After taking some time to think about it, I'm going to close this issue. I'm trying to keep my implementation of this library as general as possible and features like this would be very specific to my implementation. If I were to implement wildcards or even support frequent cache-invalidation when reply_uris changes, I'm not certain this would be supported by other OP libraries or identity-as-a-service providers if I choose to use those in the future.

In my use case these host names for specific tenants really just point back to instance host names. Tenants could have their own instance but more than likely share an instance. I'll make changes to my RP to allow it to receive the OIDC reply with uris that use the instance specific host name. In this way the reply_uris metadata is just as unchanging as the rest of the client metadata and I won't have to worry about how this will scale.

**Comment by panva** [comment]
> I'll make changes to my RP to allow it to receive the OIDC reply with uris that use the instance specific host name.

Don't forget that should your RPs be supporting multiple IdP connections it is best practice to have unique callback routes for each.
