### ISSUE TITLE
multiple client authorizations

### ISSUE THREAD

**Issue by adrai** [panva/node-oidc-provider#279]
How do I have to configure the client settings, to have the possibility to get the authorization code only with the clientId but request the accessToken/idToken with clientId and clientSecret (via POST body)?

**Comment by panva** [comment]
Hi @adrai,

to get an authorization code you never need a secret, since this one is returned by the authorization_endpoint.

To set one of the client [authentication methods](http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) for a token_endpoint use the values for `token_endpoint_auth_method` client property as per [Registration 1.0](http://openid.net/specs/openid-connect-registration-1_0.html).

You can also fine-tune the method for introspection and revocation respectively with `introspection_endpoint_auth_method` and `revocation_endpoint_auth_method`
