### ISSUE TITLE
Password Grant Type

### ISSUE THREAD

**Issue by flyweight** [panva/node-oidc-provider#28]
The password grant type example currently only responds with an access token.  Looking at the other examples, it isn't inherently obvious how to also include refresh and id tokens with it as well.  Does it make sense to also include these tokens?  Could you please demonstrate how to accomplish this?

**Comment by panva** [comment]
It's really nothing more than a subset of [lib/actions/token/authorization_code.js](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/token/authorization_code.js#L58-L117) with the exception that you do not want properties to be carried over from authorization code but rather pass the ones you want in a parameter. i.e. scope. You can access a random `grantId` by `this.oidc.uuid`, `authTime` should be probably be assigned as `parseInt(Date.now() / 1000)`, claims should not be set at all and so on. Since this is a non-oidc defined area and password grant type is in general discouraged from being used i would not provide a more complete example in the README. Let me know if you have further questions/issues, otherwise please close. Would be cool if you opened a wiki page with your resulting code or others to benefit from.

**Comment by flyweight** [comment]
Where can I get these values, or do I generate them myself?

code.acr
code.sid

**Comment by panva** [comment]
i don't believe you need them for password grant type

**Comment by flyweight** [comment]
Works for me.  I will see what I can come up with.  Thanks for the help.

**Comment by panva** [comment]
you're very welcome

**Comment by flyweight** [comment]
You mentioned that OpenID Connect doesn't support Resource Owner Password Creds, but this answer states otherwise:

http://stackoverflow.com/questions/24047047/does-openid-connect-support-the-resource-owner-password-credentials-grant

If it's not supported, how else are you supposed to authorize trusted, 1st party applications - do you expect users to have to go through 3-legged auth?  Resources:

https://alexbilbie.com/images/oauth-grants.svg
https://alexbilbie.com/guide-to-oauth-2-grants/

**Comment by panva** [comment]
This feature can become very opinionated, that's why i don't provide an out-of-the-box version of this grant.

There are implementations out there that only provide access_token, some that provide refresh too, some that accept the scope parameter, some that don't, oauth2 does not recognize id_token. 

The account model required for this library is very simple - find by id and return claims, there's no way you can get by with this minimal API and support finding by username and comparing password hashes for a broad range of applications out there, some use bcrypt, some scrypt, some would like to use AD. That's why if you wish to have password grant type you need to provide the implementation yourself.

**Comment by flyweight** [comment]
You can still send id_token and OAuth2 consumers can just ignore it.  For the password hashing, you can just expose another method off of the account model where each can add their own implementation `findByLogin` can take an optional parameter of `password` for example or a new method `findByLoginAndPassword` could be added.

Either way, I think it would be incredibly beneficial to add it, even if it's only an example implementation.

**Comment by panva** [comment]
Also see #14 for previous discussion around ROPC

**Comment by haoruiqian** [comment]
Following https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#custom-grant-types I can add support for password grant type, and generate refresh token as well inside the handler, but how could I use it to get a new access token?

I created a client which supports grant types "password" and "refresh_token", but it violated the rule https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/client_schema.js#L220, refresh_token grant type must be used in combination with authorization_code grant type, so I added authorization_code to the supported grant types as well, then it required redirect_uris, which I  didn't want to set because this client was just for password grant type and should not have redirect_uris.

Then how could I use this refresh token to get a new access token?

**Comment by panva** [comment]
Clearly an oversight, please open an issue.

**Comment by panva** [comment]
@haoruiqian this is fixed in 1.15.12, i just lifted the validation - please keep in mind the use of password grant type is discouraged, hopefully you need it to protect a confidential and secure component of your IDP, otherwise password scraping by clients (such as as confidential websites, let alone public native apps!!!) is considered a bad practice

**Comment by marc0s** [comment]
Sorry to bump this one after so long, but I'm doing some tests before adopting `node-oidc-provider` and have a similar problem while implementing the `password` grant (which sadly we still have to support) as indicated in the docs https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#custom-grant-types And I didn't found the issue you asked to open.

I couldn't find no indication on how client validations should be overriden for the new grant type's parameters.  Is this something not expected to be done and should I add custom code to the `client_schema.js` file?

By only registering the new grant type as in the docs above, I get the following error on startup `grant_types can only contain members [implicit,authorization_code,refresh_token]` (added custom `debug()` call for getting more information about schema errors).

Thanks a lot!

**Comment by panva** [comment]
You don’t have to make any changes to client schema. Just register the grant before initialize (should you still use static clients not in your adapter store).

**Comment by marc0s** [comment]
@panva thanks a lot, I was registering it on the `initialize().then(` block.

**Comment by panva** [comment]
There you go. You’re welcome.
