### ISSUE TITLE
Passing custom object to interactionfinished. 

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#286]
Hi @panva , I am trying to send json in interactionFinished - > login -> account os that I can do some further processing internally. Is this fine to use this way or it will break in future? 
```
var accountJson={
"firstName":"Value1",
"lastName":"Value2",
"accountId":'12342"

};
       Provider.interactionFinished(req, res, {
            login: {
                account:  accountJson,
                acr: '1',
                remember: false,
                ts: Math.floor(Date.now() / 1000),
            }
        });
```
Thanks.

**Comment by panva** [comment]
Account should be a string, beyond that you're in an uncharted space and i can't tell you either if it's fine or if it won't break in the future.

Set your account properties out of bands as part of your interactions is my suggestion. To pass meta details and have them available in the resume route and in all user-agent related flows use the meta property.

**Comment by codestorycooked** [comment]
Thanks @panva 

I tried the approach you suggested as below: 

```

var accountJson={
"firstName":"Value1",
"lastName":"Value2",
"accountId":'12342"

};
       Provider.interactionFinished(req, res, {
            login: {
                account:  accountJson.accountId,
                acr: '1',
                remember: false,
                ts: Math.floor(Date.now() / 1000),
            },
       meta:{
          accountInfo:accountJson
            }
        });

```
but when I do `findById` I get an error saying `meta is undefined`

```
public findById = async (ctx, id, token) => {
      let  accountInfo=ctx.oidc.result.meta;
        return {
            accountId: id,

            async claims() {
                 return { firstName: accounInfo.firstName, lastName:accountInfo.lastName };
            },
        };
    }

```
Can you help me with this. What I am doing wrong here?

**Comment by panva** [comment]
For one accessing ctx.oidc.result.meta is not my recommendation. `ctx.oidc.session.metaFor(clientId)` is.

Second, do you understand this is stored on the user-agent session and will therefore only be available in contexts where findById is called from i.e. the `authorization_endpoint`? It will never be accessible from a `token_endpoint` call since the user's session is not loaded there at all.

What you're doing is bad design, the account's claims should be stored on the account, not on the session. Your interactions should be setting those claims on whatever account storage you have.

Also:
> For instance i think it should be possible to store the user choices for that given interaction (key would be the grant id (in the url)), and load those based on the token's grantId that you get as a param the findbyid.
