### ISSUE TITLE
id_token does not include claims other than sub claim when response type is "id_token token"

### ISSUE THREAD

**Issue by pkeuter** [panva/node-oidc-provider#330]
First, thanks for this awesome lib!

When specifying response type `id_token token`, the scope will be set to fixed `openid` instead of `openid <claims>`. The "problem" seems to be here: https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/process_response_types.js#L73

I am not 100% sure if this is the expected behavior, but I would say that when I ask for an id_token, I should expect the scopes included in the token. Am I correct?

Anyways, if this is the case, changing the equality comparison to a split by space and then check comparison would be a pretty simple fix.

I would gladly provide a PR, but please tell me if it's necessary.

**Comment by panva** [comment]
Only response types not ending up with an access_token (`id_token`) have end-user claims in the id tokens. Otherwise you're supposed to fetch them with the access token. This is the Core 1.0 spec behaviour.

As seen in the code and defaults this was not the case until v4.1.0 with the (by default off) `conformIdTokenClaims` feature flag. In future major (v5.x) updates this will be flipped to on by default but the flag will stay to support the non-conform behaviour of always including end-user claims in an id token.

**Comment by panva** [comment]
The relevant part of the spec is http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims 
Read very carefully and you'll see requesting claims through the scope parameter only adds these claims to userinfo unless the response_type is `id_token` in which case they're added there.

**Comment by pkeuter** [comment]
@panva I see. Thanks for the clarification! It's actually stated pretty clearly in the spec.

**Comment by panva** [comment]
Well. Up until a few releases ago I didn’t realize, hence the feature flag ;)

**Comment by David-hod** [comment]
I think we should also document this flag since there is not information about it on : [https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md)

I wasted 3 hours debugging the code until I saw this flag in the code. then i came across the issues and saw this issue which is exactly what I was facing.

**Comment by panva** [comment]
@David-hod 
In v6.x this is no longer a "feature" configuration but rather root configuration property and it is exposed on the configuration page.

The [FAQ page](https://github.com/panva/node-oidc-provider/wiki/FAQ#id-token-does-not-include-claims-other-than-sub) also lists this as the first point and i'll be moving all FAQs to the bottom of both the readme and configuration.md files.
