### ISSUE TITLE
Thank you very much for your module node-oidc-provider

### ISSUE THREAD

**Issue by acodercat** [panva/node-oidc-provider#335]
Thank you very much for your module node-oidc-provider.
I'd like to make a few suggestions here for you:
1. We want to not handle HTTP exceptions inside Node-oidc-provider, just throw exceptions

2. Make Node-oidc-provider try not to be coupled with KOA or express.

We now want to develop based on Node-oidc-provider, but we can't catch exceptions for processing. thanks~

**Comment by panva** [comment]
I don’t get the need to *catch* exceptions. If you just need to debug your own code look at the debugging section in the readme. 

Otherwise exceptions are handled the way the protocol dictates and I won’t consider it any other way. 

oidc-provider is written using koa, if you’re going to write custom code it might be useful to know koa but in general for interactions you can write them in whatever you want. As far as middleware’s go, I aint going to reinvent the wheel by coming up with a custom solution. I refer you to koa or reading the codebase to learn how to deal with it. 

If you’re looking for a solution that doesn’t do the full protocol works for you, you might want to look for a different package.
