### ISSUE TITLE
Custom properties for InitialAccessToken with extra validation

### ISSUE THREAD

**Issue by apparentvisuals** [panva/node-oidc-provider#394]
**Is your feature request related to a problem? Please describe.**

When registering clients using an InitialAccessToken, I would like to be able to validate the client metadata against values in the InitialAccessToken to ensure the client only registers what they requested as part of the InitialAccessToken request.

If this is something that sounds like a good feature to you, I also do not mind submitting a pull request for review and I am open to alternative way to achieve the same result.

**Describe the solution you'd like**

- Allow InitialAccessToken payload to be extended with extra values.
- Allow an optional validator to be passed into the registration flow to validate the access token

**Describe alternatives you've considered**

- Have currently implemented using a pre-middleware to perform validation of the token content and modify req.body of the incoming client metadata accordingly, but this requires an extra load of the token from DB.

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Hi @apparentvisuals 

> If this is something that sounds like a good feature to you, I also do not mind submitting a pull request for review and I am open to alternative way to achieve the same result.

I already have this in my private backlog so it definitely does sound like a great feature.

Posting my private notes 👇 

There are two things the initial access token should be able to carry

**1. defaults for properties**

- Simple, if a property wasn't provided (is undefined) the default from IAT is applied.

**2. policies**

- E.g. only register pairwise
- E.g. only allow RS* algs etc
- what's the easiest way to accomplish this so that it's dynamic enough?

I'm thinking we need to elaborate on the different options we have for nr. 2


Options I see, welcome your thoughts and other ideas

- we define a custom json structure for the known policies we wish to implement
- we allow a property on the token (in db) with a js code we eval during runtime - i hate this idea, but it's as dynamic as it gets.
- we allow a property on the token (in db) with a reference to a policy implementation (many may be present) that will be present on the provider configuration and that one gets executed (i like this one the most)

If the third option is the prevalent one it can be used for both policies and defaults and allows it to be easily referenced and also allows for those policies and defaults to be ran during client#update, meaning that the policy identifier would also be stored on the registration access token and kept when those are rotated.

**Comment by panva** [comment]
> Have currently implemented using a pre-middleware to perform validation of the token content and modify req.body of the incoming client metadata accordingly, but this requires an extra load of the token from DB.

This is what i've been doing so far too. The drawback isn't that bad. But i have to implement it both to registration and update separately.

**Comment by apparentvisuals** [comment]
> we allow a property on the token (in db) with a reference to a policy implementation (many may be present) that will be present on the provider configuration and that one gets executed (i like this one the most)

If I understand you correctly, we would have a new data type say RegistrationPolicy that can be retrieved via the adapter and the id would be stored in the IAT. This value can contain policies as well as defaults.

I was also thinking something more simple like exposing a method through provider configuration could work, something like:

`
async validateClientRegistration(ctx, iat, metadata) {
  ...
  return metadata;
} 
`
Leave it up to the implementer to determine what the policies should be, whether iat values are defaults, or they are used to validate against the value in client metadata or anything.

**Comment by panva** [comment]
> If I understand you correctly, we would have a new data type say RegistrationPolicy that can be retrieved via the adapter and the id would be stored in the IAT. This value can contain policies as well as defaults.

Not a data type stored in the DB. the IAT would have a string reference to a policy, that policy will be declared during provider configuration and ran every time an IAT is used to register or every time a client is updated (the policy reference would transfer from IAT to RAT (reg. access token).

> I was also thinking something more simple like exposing a method through provider configuration could work, something like:

also an option, but one that is less "framework"-y. Let me write down a design doc and of what i'd accept and if you wanna contribute, you can, if not, that's fine and i'll work on it when i have the time.

**Comment by apparentvisuals** [comment]
That sounds good. I can review the design doc and then I will likely understand your design better.

In your design, would policy still be dynamic? The immediate way I would use this feature would be for tenant bound IAT so the tenant would be part of the payload such that no other tenant (unless they knew the tenant name and secret) so I wonder if the policy design would cover the use case.

**Comment by panva** [comment]
> In your design, would policy still be dynamic? The immediate way I would use this feature would be for tenant bound IAT so the tenant would be part of the payload such that no other tenant (unless they knew the tenant name and secret) so I wonder if the policy design would cover the use case.

Please elaborate if necessary, but a policy's implementation is dynamic - it's your function that will get executed.

**Comment by panva** [comment]
wip https://github.com/panva/node-oidc-provider/compare/master...feat/registration-policies

please let me know what you think before i proceed
