### ISSUE TITLE
How to access interaction result data from findById?

### ISSUE THREAD

**Issue by brandonros** [panva/node-oidc-provider#398]
My finishInteraction looks like this:

```
const finishInteraction = async (req: express.Request, res: express.Response) => {
 ...

  const userId: string = await retry({
    fn: () => resolveUserId(fiUrl, jwt, xForwardedFor),
    maxAttempts: 10,
    delayMs: 1000
  })

  const user = await retry({
    fn: () => getUser(fiUrl, jwt, userId, xForwardedFor),
    maxAttempts: 10,
    delayMs: 1000
  })

  const interactionResult = {
    login: { account: userId, user: user }
  }
  const provider: Provider = getProvider()
  await provider.interactionResult(req, res, interactionResult)

  return new HTTPResponse('', {
    location: `${OIDC_URL_PREFIX}/oidc/auth/${interactionId}`
  }, 302)
}
```

Later on, oidc-provider calls `findById` (multiple times).

How can I pull up `interactionResult.login.user` reliably from `findById`? Do I need to key off of a `ctx.oidc` entity?

**Comment by brandonros** [comment]
It seems like the interaction result is stored in a Session record. From there, it is turned into a AuthorizationCode record with the same ID, but the Session record is deleted...

How can I achieve what I am trying to achieve?

**Comment by panva** [comment]
As you can see in the [documentation](https://github.com/panva/node-oidc-provider/blob/v5.3.0/docs/configuration.md#interaction) the result's login section is well defined and while you may be able to reach the result in some scenarios, it's not supported.

Your best shot for something that does reach the session (for requests that come from the end-user's user-agent and are intended to work with a session) and has a client id namespace is the meta.

> How can I pull up interactionResult.login.user reliably from findById? Do I need to key off of a ctx.oidc entity?

Even with using `meta` - keyword there is **reliably**, and the fact is, while inside e.g. userinfo or token calls, you won't have access to a session because those are not session based calls. The point of the method is to load the account by id and nothing else first and foremost. You shouldn't need anything else.

> How can I achieve what I am trying to achieve?

Based on this and your past issues I'm actually not sure what you're trying to achieve, sorry.

**Comment by brandonros** [comment]
> while inside e.g. userinfo or token calls, you won't have access to a session because those are not session based calls.

Those calls are all linked to a common grant/sessionId, no?

Why is this package overriding the original interaction result through the adapter, I guess is my question.

I'm trying to achieve user resolution but findById doesn't work for me because my user resolution process isn't as stateless as that function design would like. It depends on incoming request headers + cookies and I am trying to avoid having to introduce distributed cache when this package already has a) the data and b) access to persistency through the database.

**Comment by panva** [comment]
You won't be able to access anything from the session, which is tied to end-user's user-agent and access it within token or userinfo calls.

> Why is this package overriding the original interaction result through the adapter, I guess is my question.

It's not overriding anything, interaction session is short term, afterwards the well-defined parameters are transformed into properties in a regular end-user user-agent bound session.

> I'm trying to achieve user resolution but findById doesn't work for me because my user resolution process isn't as stateless as that function design would like.
> It depends on incoming request headers + cookies
> I basically want to call interactionDetails after an interaction has been finished, as it is being turned into a userInfo/token/auth call

Probably look for a different oidc provider then. If you can't make an account `find by id` work you won't be able to have token/userinfo as i stated before and re-iterating now, those calls do not depend on cookies nor headers.
