### ISSUE TITLE
Scopes in login handler?

### ISSUE THREAD

**Issue by flyweight** [panva/node-oidc-provider#40]
In the login handler in the example (https://github.com/panva/node-oidc-provider/blob/bbf3ce8418f62c19527d313a83f04ad3b181a86b/example/index.js)

router.post('/login', body, function* submitLoginForm() {

What is the easiest way to get access to the scopes being requested?  The grant uuid is available there, is there a helper method that can be used to get the scopes?

Thanks

**Comment by panva** [comment]
no generic helper from the library is available since your interaction MAY be a) different app, b) different frameworks, c) not node at all. You can get details on the interaction from the signed (hopefully) cookie.

`const cookie = JSON.parse(this.cookies.get('_grant', { signed: true }));`

this includes details on the reason why OP stopped authentication and requested interaction as well as the recognized parameters of the original request (including scope which you're after)

**Comment by flyweight** [comment]
Thanks for the fast response.  I first tried to pull it from the cookie before writing.  Unfortunately, the cookie has a path set on it.  Therefore, it isn't available to the `/login` route.  Is there a particular reason the path is being set and restricted to the `/interaction/:grant` endpoint?

```javascript
      this.cookies.set('_grant', j(ctx.params), Object.assign({
        path: provider.pathFor('resume', { grant: ctx.uuid }),
      }, cookieOptions));
```

**Comment by flyweight** [comment]
For anyone that may land here, to circumvent, I just changed the login endpoint to look like:

`router.post('/interaction/:grant', body, function* submitLoginForm() {`

and the action in GET '/interaction/grant' to:

`action: `/interaction/${this.params.grant}``

**Comment by panva** [comment]
Hello,

yes, there is a good reason for this default - cookies get overwritten and i wanted to offer a non corner case having interaction examples.

There's also a way for you to configure the path or even send the user-agent to a different domain using a [configuration option](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L281-L292). Using this you are able to send the user to just /login. I do however recommend to namespace with the grantId so that your cookies don't get overwritten and a single user can open multiple interactions without breaking the previous ones which aren't finished.

**Comment by panva** [comment]
Ah, i get it now :) the example actually does NOT namespace the submit forms. I'll correct that, it should!
