### ISSUE TITLE
Claims in JWT Access Token

### ISSUE THREAD

**Issue by chungath** [panva/node-oidc-provider#423]
Environment:
- oidc-provider version: [5.0.0]
- node version: [8.11.3]

We are using the configuration given below to generate the access token as a JWT token.
` formats = { default: 'opaque', AccessToken: 'jwt' }; `

In our case, the RP sends the access token to another service which validates the accessToken using the certificate from OP's jwks_uri.

Now, when the Service validates the JWT token to get the claims, the following claims are in the payload.
- jti
- sub
- iss
- iat
- exp
- scope
- aud

We want to add more claims (Like email, tenantName etc.) in the JWT token so that those are available to the Service which is validating the token.

Please let us know how these additional claims can be specified in the JWT Access Token.

**Comment by panva** [comment]
- #330
- https://github.com/panva/node-oidc-provider/wiki/FAQ#id-token-does-not-include-claims-other-than-sub

**Comment by chungath** [comment]
I made  a mistake on the description, it is not the RP which is validating the token, the RP is sending the access token to another Service which is validating the token. I have corrected the description now.

**Comment by panva** [comment]
> Please let us know how these additional claims can be specified in the JWT Access Token.

Not out of the box and I don't plan to somehow make it easy-configurable.

You may however overload `provider.AccessToken.prototype.getValueAndPayload` method. This is public API - see [here](https://github.com/panva/node-oidc-provider/blob/master/lib/models/base_token.js#L153-L163).

For reference, the one used by the jwt format is [here](https://github.com/panva/node-oidc-provider/blob/master/lib/models/formats/jwt.js#L42-L67).

**Comment by chungath** [comment]
Thanks for the pointer!

Looking at it further, the accessToken payload seems to be containing [claims ](https://github.com/panva/node-oidc-provider/blob/v5.0.0/lib/actions/grants/authorization_code.js#L69) which is a copy of the claims property of Authorization Code.

The claims property in Authorization Code seems to be set as per the claims parameter in the request if 
features.claimsParameter is enabled. [oidc.resolvedClaims()](https://github.com/panva/node-oidc-provider/blob/v5.0.0/lib/actions/authorization/process_response_types.js#L42) being the one which gets called to get these claims.

So, if I have to add these additional claims like email, tenantName etc. into the JWT accessToken, I will have to do the following

- Enable features.claimsParameter
- RP should pass these additional claims in the request(claims query parameter)
- overload provider.AccessToken.prototype.getValueAndPayload to set these claims(email, tenantName etc. ) into the JWT payload by reading from the claims property in the accessToken(Basically from the opaque payload).

 Is my understanding correct?

**Comment by panva** [comment]
> Is my understanding correct?

Unfortunately it isn't. The claims parameter has nothing to do with a jwt access token payload and neither does it mean the claims will be available because the client requests them.

The only thing that matters is the `provider.AccessToken.prototype.getValueAndPayload` result's first member representing the value that's returned.

**Comment by chungath** [comment]
Ok, so we can just override the **value** in the return value [value, payload] of getValueAndPayload.

Now, once we have the overloaded method, it will need the references to the classes for [opaque](https://github.com/panva/node-oidc-provider/blob/master/lib/models/formats/opaque.js) and [jwt](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/jwt.js) so that we can get the opaque payload, add the extra properties and then sign it using the JWT helper to create the value.

Are these classes - [opaque](https://github.com/panva/node-oidc-provider/blob/master/lib/models/formats/opaque.js) and [jwt](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/jwt.js) - available for us to use?

**Comment by panva** [comment]
Nope, thats why i said this isn't something out of the box supported and you'll have to write your own format using the [public API](https://github.com/panva/node-oidc-provider/blob/v5.5.2/lib/models/base_token.js#L143-L195) for this, you don't need to use the library's internals to achieve that, in fact, requiring files from within the library structure which isn't mentioned by the documentation may very well lead to incompatibility between minor/patch versions since i'm allowed to change those at will.

A simple hacky way of doing this would be to keep a reference to the original `getValueAndPayload ` method, invoke it, get the value and payload and then just return a different value JWT (don't forget to assign this new value to payload.jwt). You don't need to sign using the internal jwt helper, you can use whatever and pass it the same key you already have access to.

Yes this means you'll be signing twice, that's why it's hacky.

**Comment by amaciver** [comment]
@chungath did you ever resolve this? Would love some insight into how you successfully overloaded the method.

**Comment by panva** [comment]
I'm locking this, there will be a helper for additional jwt **access token** claims in [v6.x](https://github.com/panva/node-oidc-provider/issues/419)
