### ISSUE TITLE
Interaction cookie 

### ISSUE THREAD

**Issue by stavros-wb** [panva/node-oidc-provider#434]
Hello @panva,

I see that after an interaction is finished the `resume` cookie is nullified:

https://github.com/panva/node-oidc-provider/blob/v4.8.2/lib/actions/authorization/resume.js#L47

But this is not the case for the `interaction` cookie. Is there a specific reasoning behind this decision?

Thank you

**Comment by panva** [comment]
Yes, because the resume route has no reliable way to form the clearOpts (domain, path, etc), i recall this is a very niche edge-case i encountered when running interactions in a different app with different subdomain, port etc.

That being said, maybe the interaction object could have options stored from when they were originally set. I'll try and get that in the next major version.

If you want to "tidy up" today you may safely remove the cookie in your interactions when you're submitting results.
