### ISSUE TITLE
Expose Adapter for client cache

### ISSUE THREAD

**Issue by davidnghk01** [panva/node-oidc-provider#440]
**Is your feature request related to a problem? Please describe.**
Currently the client cache [has hardcoded](https://github.com/panva/node-oidc-provider/blob/b56a795b7274f72ec33af55853d2182bbdb3fc22/lib/models/client.js#L177) with in-memory cache, it would cause data inconsistent issue because when client on DB get updated the [cacheClear function](https://github.com/panva/node-oidc-provider/blob/b56a795b7274f72ec33af55853d2182bbdb3fc22/lib/models/client.js#L425) only able delete cache in current process. It make no sense when API is deployed on distributed system.

**Describe the solution you'd like**
Like another cache/ perishable item like AccessToken, Client, ClientCredential  ...etc. It should provide the adapter interface for change the storage behaviours.

 - i have searched the configuration section for this feature and couldn't find it
 - i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Hi @davidnghk01,

the purpose of the cache is to avoid having to instantiate the internal `provider.Client` model because there are some potentially expensive operations tied to loading it (e.g. fetching sector_identifier_uri).

If a cache like you describe was in place that's not covered because I assume you're just thinking of something like memcached or redis for distributed cache. But that's no different from the actual storage adapter you already have.

I have some plans for this in v6.x. It will be possible to disable the `clientCacheDuration` by setting it to false. When false is configured the client will always be fetched from the existing adapter and re-instantiated only if the hash of the returned object changes. Ergo cache will still be there but it's invalidation will be controlled by changes in the storage.

For now, I've always been able to have a pub/sub outside of the provider configuration which would listen for events emitted by something in your infrastructure that would just call `cacheClear` with the specific client id that changed. Or, if you're not using the client properties that require computation (fetching client's jwks_uri or sector_identifier_uri) you're fine just setting the cache duration to something really low, like 15 seconds?

WDYT?

**Comment by davidnghk01** [comment]
@panva That sound good, my current solution is disable cache by set `clientCacheDuration` to `0`.

Just curious how did compute the 'hash' ? By all attribute return from adapter ? By `sectorIdentifierUri` and `jwks` ? (Seem it is two attribute which related to `potentially expensive operations`) ?

**Comment by panva** [comment]
I'm not gonna vouch for `clientCacheDuration: 0` because i'm not sure if it disables it or makes all items seem expired. To be sure lru-cache does explicitly mention setting it to negative value will do the thing you want for sure, assuming you understand its effects.

ad client hash, i'll use the same mechanism for calculating client session states, using [object-hash](https://www.npmjs.com/package/object-hash) to get consistent results regardless of property or array member order.

So we're good to close?
