### ISSUE TITLE
custom CORS rules support?

### ISSUE THREAD

**Issue by acappella2017** [panva/node-oidc-provider#447]
oidc-provider supports CORS for userinfo/certificates//discovery endpoints. But it allows all origins.

We are trying to register a CORS middleware to customize the supported origins. Like this:

```
provider.use(corsMiddleware());
```

But the customized origins settings will alway be overrided by oidc-provider's own cors settings...

Is there any suggested way to register CORS middleware for oidc-provider? or is there any plan to add settings to disable the default CORS settings?

**Comment by panva** [comment]
> But the customized origins settings will alway be overrided by oidc-provider's own cors settings...

You sure? If your middleware doesn't yield next during preflight than preflight should be fine. The actual request then i agree, will overwrite, but you can handle that with a custom middleware, it just needs to be tailored to how the provider works.

Can you provide the definition for your `corsMiddleware`?

> Is there any suggested way to register CORS middleware for oidc-provider? or is there any plan to add settings to disable the default CORS settings?

I don't have a suggested one, CORS is supported and i fail to see the need to restrict calling some of those endpoints just from some origins. I don't plan on adding any customization because i believe a custom middleware can handle that, its just that i think your middleware is a generic package that's bound not to work.

Altho, 🤔 maybe the cors middleware of oidc-provider should just passthrough when custom settings are already on the response object.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/compare/cors-passthrough

wdyt @acappella2017?

**Comment by acappella2017** [comment]
> > Altho, 🤔 maybe the cors middleware of oidc-provider should just passthrough when custom settings are already on the response object.
> 
> https://github.com/panva/node-oidc-provider/compare/cors-passthrough
> 
> wdyt @acappella2017?

This patch works for me. 😊 Great thanks!
Will it be in the official code?

**Comment by panva** [comment]
Yes. With the next v6.0.0 alpha

**Comment by panva** [comment]
@acappella2017 I think custom CORS implementation is no longer necessary with v6.0.0 (now in alpha.1)

See https://github.com/panva/node-oidc-provider/blob/2418029/docs/README.md#clientbasedcors and https://github.com/panva/node-oidc-provider/commit/8b4fd9e

With this new helper function you control whether CORS request should be allowed or not on a per-request(+client) basis for the endpoints that matter (token, userinfo, revocation, introspection, etc). Restricting discovery and jwks makes no sense.
