### ISSUE TITLE
[Question] How to use oidc-provider as keycloak identity provider

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#462]
Im trying to use a node oidc-provider app as an identity provider for my keycloak server.
So far i cant get it working.
Keycloak throws an exception telling me that my oidc-provider app doesn't return an access token.

For more information please look at the question I posted at stackoverflow:
https://stackoverflow.com/questions/56055415/node-oidc-provider-for-keycloak

Do I have to configure the token endpoint in my app to return propper access tokens?
I'm just getting into the whole OAuth/OIDC framework and I am still struggeling a lot...

**Comment by panva** [comment]
Hi @bob-sheknowdas 

> org.keycloak.broker.provider.IdentityBrokerException: No access_token from server.

Is rather generic and you could for instance run `DEBUG=oidc-provider:*` as the README suggests before reaching out for help, it would give me more insight, and yourself a chance to figure out the problem on your own.

However, it seems unlikely that keycloak is not using the provided `client_secret` to authenticate, in which case they call the token endpoint with either `client_secret_basic` or `client_secret_post` authentication method and oidc-provider will fail the request because it expects NO secret due to your client setting `token_endpoint_auth_method: 'none'`.

Try setting `token_endpoint_auth_method` to either `client_secret_basic` or `client_secret_post` depending on what keycloak is using.

**Comment by bob-sheknowdas** [comment]
Setting the token_endpoint_auth_method to client_secret_post was solution.

I've already experimented with client_secret_basic, but simply gave up when that didn't work.

Anyways, thanks a lot for the fast response.
Appreciating it.
