### ISSUE TITLE
End session with post_logout_redirect_uri but without id_token_hint

### ISSUE THREAD

**Issue by RasmusFredensborg** [panva/node-oidc-provider#464]
Hi,
Thank you for this amazing OIDC implementation. I've been extremely happy with the amount of customisation and the level of OIDC compliance this implementation provides.  
  
I'm using session management, and I'm trying to have an RP initiate a logout **without** an id_token_hint but **with** a post_logout_redirect_uri in the end_session query parameters. Looking into the code (```end_session.js``` line 52 to 78), I can clearly see that this is not currently supported (using v5.5.3):
```
if (params.id_token_hint) {
  ...
} else {
  params.post_logout_redirect_uri = undefined;
}
```
However as I understand, the OIDC spec does not imply that the post_logout_redirect_uri is dependant on the id_token_hint, so my feature request is this:  

**If a post_logout_redirect_uri query parameter is supplied to the end_session endpoint, it should be honored _if_ said post_logout_redirect_uri is registered with any OIDC client.**

**Comment by panva** [comment]
Hi @RasmusFredensborg 

> However as I understand, the OIDC spec does not imply that the post_logout_redirect_uri is dependant on the id_token_hint.

> If a post_logout_redirect_uri query parameter is supplied to the end_session endpoint, it should be honored if said post_logout_redirect_uri is registered with any OIDC client.

Such lookup is not efficient and possible with the minimal requirement for document lookup via the adapter.

However, my understanding was the same and I attempted to [convince](https://bitbucket.org/openid/connect/issues/1032/rp-initiated-logout-proposal-for-client_id) the authors to define a client_id parameter in case that hint is not provided and uri was so that efficient client lookup and hence post logout uri whitelist validation was possible.

This was a lengthy discussion in the OIDC issue tracker, in several calls as well as in person meetings. The outcome is that not having and id_token at hand is perceived as a deficiency on the client software.

Since RP-initiated logout is not final, in recent months it was agreed that an rp-initiated end-session request with post logout uri and no id token hint is not intended and will be clarified as such in the next document update.

> https://bitbucket.org/openid/connect/issues/1071
> During IETF 104 in Prague, a number of us discussed RP-initiated logout and how to validate the client so that redirecting to the post_logout_redirect_uri is safe. The consensus was to require that an id_token_hint be present so that the client can be validated; otherwise, the supplied post_logout_redirect_uri should not be honored.

In v6.0.0-alpha.x this is already [in place](https://github.com/panva/node-oidc-provider/commit/b3a50ac).
