### ISSUE TITLE
reading Provider instance configuration

### ISSUE THREAD

**Issue by flyweight** [panva/node-oidc-provider#48]
Can't find an easy way to grab the configuration variables for a given provider to do the following check:

`instance(provider).configuration('features.refreshToken')`

In order to get access to the provider configuration method, I had to do load the following:

`const instance = require('../lib/node_modules/oidc-provider/lib/helpers/weak_cache');`

Is there a better way to load the provider instance?

**Comment by panva** [comment]
The configuration getters setters were never documented to be a part of the public api, didn't intend them to be changed during runtime so i made them private in 1.0;

Are you running multiple providers in one process that may or may not have always-issued refresh tokens?

**Comment by flyweight** [comment]
Yes, that's the only property that I need to check against currently.

**Comment by panva** [comment]
I guess there will be more valid reason to read the provider config during runtime eventually. I will refactor the configuration interface and expose the getters for 1.5.x

**Comment by panva** [comment]
Out of curiosity, what's the grant type you're preparing and what's the feature flag telling you?

**Comment by flyweight** [comment]
Grant type is password (ROPC).  For this provider, refresh tokens are disabled, so the features.refreshToken is resolving false.

**Comment by panva** [comment]
But the feature flag means something else in the context of out of the box authorization / grants. 

refresh_token grant is always pushed/enables if you support offline_access scope. The flag makes it so that refresh tokens are issued and grant enables even if the scope is not present.

I would suggest you check what you need on a client level - if the client has grant type refresh token, issue it, otherwise don't. You can access the client via this.oidc.client in the grant. Afterall a client w/o the grant can't use the token anyway. 

What do you think?

**Comment by flyweight** [comment]
That sounds like a more intuitive approach and should be really easy to implement within the context of the add grant method.  Thanks for the help.

**Comment by panva** [comment]
Happy to help. I will prepare two things

- an faq on these common questions about refresh tokens, grants etc
- the configuration getter
