### ISSUE TITLE
Custom token_type response

### ISSUE THREAD

**Issue by brandonros** [panva/node-oidc-provider#482]
**Is your feature request related to a problem? Please describe.**
Only `Bearer` token_type response is available now (it is hardcoded here: https://github.com/panva/node-oidc-provider/blob/ed81fc64b5d6119489ef1021aebd71f2db44018e/lib/actions/grants/authorization_code.js#L164)

**Describe the solution you'd like**
The ability to configure custom `token_type` response values.

**Describe alternatives you've considered**
Hooking koa.js middleware / `res.end` to modify the response

**Additional context**
Is this available in 6.0?

 - [X] i have searched the configuration section for this feature and couldn't find it
 - [X] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
What token type would you return? How would you make the OP have additionally process different token types?

Only Bearer token is defined for OAuth2 and OIDC which is why i’m asking. The moment more token types will be available (such as DPoP, it’ll be handled). Until then this is not for customizing.

**Comment by brandonros** [comment]
If you can add either a custom configuration value or even change the code to be `process.env.TOKEN_TYPE || 'Bearer'`, it'd be a massive help to me.

From https://stackoverflow.com/a/6033840/4971709:

```
Anyone can define "token_type" as an OAuth 2.0 extension, but currently "bearer" token type is the most common one.

https://tools.ietf.org/html/rfc6750
```

**Comment by panva** [comment]
I'm afraid that's not a reason enough for this. Without understanding the "why" and to what end I will not entertain the question of "how", definitely not on the base of "because i can" argument.

So I reiterate my questions:

- What token type would you return?
- How would you have the OP process the different token type at e.g. the userinfo endpoint?
- What's the point?

With every token type there come RFCs for how these are used and processed, e.g. 6750 for Bearer token usage. Future DPoP OAuth2.0 extension for `DPoP` token type, do you have a published OAuth2.0 / OIDF draft detailing a new token type?

**Comment by brandonros** [comment]
Use case:

We have two types of APIs (consumer + enterprise) at my business.

We have two oidc-providers (one for each API type)

They both return `Bearer JWT` access_tokens.

They get sent upstream to a proxy/gateway. The gateway doesn't know which oidc-provider to validate against.

I'm ok to leave token_type: `Bearer`, but maybe you expose a configuration middleware/hook that allows me to prefix the token with something?

`Authorization: Bearer enterprise:$ACCESS_TOKEN`

I feel like that wouldn't break Oauth2 clients?

**Comment by brandonros** [comment]
I also understood `Bearer` to not be a standard but a recommendation. aka `token_type` could be anything? as long as `/oidc/token` returns a string and the calling client calls back with that same string:


```
{
"token_type": "foobar",
"access_token": "..."
}
```

`Authorization: foobar ...`

**Comment by panva** [comment]
No, we must be returning Bearer to be conform. It is the only defined token type available.

If you have two providers then they have different issuers. Your APIs can look at the jwt claims, validate the jwts. This is a solved problem one that we don’t need breaking behaviours for to solve again.
