### ISSUE TITLE
Community documentation for 6.alpha interactions

### ISSUE THREAD

**Issue by kmalakoff** [panva/node-oidc-provider#485]
In https://github.com/panva/node-oidc-provider/issues/484, @panva requested documentation on interactions: 

```
@kmalakoff would you be able to contribute a few paragraphs of explanation how the interactions in v6.x work? I myself am having a hard time coming up with something readable.
```

Would anyone be interested in documenting?

**Comment by kmalakoff** [comment]
The way I used the interaction was a bit non-standard:

- I used GET '/interaction/:uid' as a redirection route to '/interaction/:uid/login' and '/interaction/:uid/consent'
- I used POST '/interaction/:uid/login' and '/interaction/:uid/consent' as pure JSON endpoints. Instead of `provider.interactionFinished` in these routes, I used `provider. interactionResult` and returned the returnTo in the JSON response so that I could handle error messages for account non-found, etc.

@panva what sort of documentation specifically are you looking for? eg. for a wiki page, usage examples, describing the changes to the API from 5.x, etc

**Comment by panva** [comment]
There's nothing v6.x specific when it comes to interactions themselves, i meant the `interaction` policy configuration property that's new. I'm going to close this because there's nothing to document, the interactions themselves are each product's / developer's playground - responsibility to implement and the only thing the library cares for is for the `Interaction` object to have its result property when redirect back to the `returnTo` happens.

**Comment by kmalakoff** [comment]
Interesting. I didn't even see the policy configuration property. I'll take a look at it!
