### ISSUE TITLE
Question: why resource allowed check recommended only on audiences? 

### ISSUE THREAD

**Issue by amaciver** [panva/node-oidc-provider#487]
Would you mind providing an explanation of why checking whether a resource is allowed on a certain client is recommended to only be done in the audiences function? 

In v6.x you are now checking the client whitelist for scope in the Auth step, why do we not want to check resources at this stage as well? For code flow, this results in a code being issued but then the token exchange being rejected. Is this the intention?

Thanks! 🙇

**Comment by panva** [comment]
> Would you mind providing an explanation of why checking whether a resource is allowed on a certain client is recommended to only be done in the audiences function?

I wouldn't say it's recommended, but at the moment it's the only helper consistently run when access tokens get issued.

> In v6.x you are now checking the client whitelist for scope in the Auth step, why do we not want to check resources at this stage as well?

`scope` is an IANA defined client property parameter, that's why a check like that is present. As you may have noticed I don't make up properties.

> For code flow, this results in a code being issued but then the token exchange being rejected. Is this the intention?

Kind of, the other way i had this running initially was that the same helper needed to be run twice, at authorization and at token requests. I didn't like that.

I think ultimately it boils down to this - the feature is still a draft and i've received very little feedback on it and myself i didn't use it enough to be able to deliver a good DX.

Thank you for bringing this up and please let me know what you would like to see. Bearing in mind it needs to work for all possible uses of resource indicators (provided in authorize, provided in token, both) and mustn't feel weird in neither, also that helpers don't get run multiple times when they don't need to.

As i'm writing this i can tell you that if you want client based policy validated at authorization request time you should register a custom client metadata property (using `extraClientMetadata`) and either run a middleware on the authorization endpoint to validate it (but you don't have the client yet loaded) or, and this may seem hacky but its perfectly valid, do the following

1) use a custom `interactions.policy`, albeit just cloned the default one.
2) add a custom `Prompt` (requestable: false) with a single Check which will run at every authorization endpoint call where you'll do said validation.

```js
const { errors, interactionPolicy: { Prompt, base: defaultInteractionPolicy } } = require('oidc-provider');

const policy = defaultInteractionPolicy();
const foobar = new Prompt({
  name: 'foobar',
  requestable: false,
}, new Check((ctx) => {
  // ctx.oidc.client
  // ctx.oidc.params.resource
  // if ctx.oidc.client['custom client property name'] doesnt include resource(s)
  // throw new errors.InvalidTarget('description')
}));
policy.add(foobar, 0); // first one checked

new Provider('...', { interactions: { policy }});
```

**Comment by amaciver** [comment]
Thanks for the clarification. Just wanted to know if I was missing something in particular. Will be happy to follow up with some indications about what would feel useful for DX. 

Will give it a shot with the Policy route you suggested.

Thanks as always!

**Comment by panva** [comment]
I failed to mention one important aspect. You like need to / should have your users consent to the resource anyway so a policy is something you’ll be putting in place anyway. Yeah. Now that i recall, that’s why.
