### ISSUE TITLE
client_credentials access_token jwt signing algorithm

### ISSUE THREAD

**Issue by mihir83in** [panva/node-oidc-provider#503]
When doing client_credentials grant, the id_token_signed_response_alg gets ignored, the generated token has RS256 alg on it. 

I am trying to use a HS256 and providing private keys on client and provider as client_secrets. The token endpoint doesn't need authentication.

Provider and Client configuration: (inline or gist)
```js
// provider configuration
{
  findAccount,
  features: {
    introspection: {
      enabled: true,
    },
    revocation: {
      enabled: true,
    },
    devInteractions: {
      enabled: false,
    },
    clientCredentials: {
      enabled: true,
    },
  },
  formats: {
    AccessToken: 'jwt',
    ClientCredentials: 'jwt',
  },
  scopes: [
    'openid', 'offline_access',
  ],
  interactions: {
    policy: basePolicy,
    async url(ctx) {
      return `/provider/interaction/${ctx.oidc.uid}`;
    },
  },
  jwks: keys,
  clients: [{
    client_id: 'sample-client',
    redirect_uris: ['http://localhost:3005/oauth/callback'],
    grant_types: ['client_credentials'],
    token_endpoint_auth_method: 'none',
    response_types: [],
    id_token_signed_response_alg: 'HS256',
    client_secret: '98257CA1D2FADD482F8411884B3A8',
  }],
}
/ keystore(s) - if they affect the behaviour
[]
// client(s) configuration
{
  client_id: 'sample-client',,
  grant_type: 'client_credentials',
  token_endpoint_auth_method: 'none',
  id_token_signed_response_alg: 'HS256',
  client_secret: '98257CA1D2FADD482F8411884B3A8',
}
```

**Comment by panva** [comment]
JWT formatted access tokens cannot be signed using a shared symmetrical secret, this is made clear from the [formats configuration option documentation](https://github.com/panva/node-oidc-provider/blob/v6.2.1/docs/README.md#formats).

I will not make that possible since everyone in possession of the shared secret can, doh, forge a token and access an RS that does only the structured token introspection rather then a server-side one.

So, working as intended.

In the future i'm also going to provide a helper for determining the algorithm (but throwing when you resolve none or HS*) since the client is not always the RS and ID Token signing alg does not always mean the RS can do the same alg validation a client can.
