### ISSUE TITLE
What is the major different between session/end and token/revocation

### ISSUE THREAD

**Issue by stanleyyuenyiu** [panva/node-oidc-provider#516]
Im using PKCE and mongo for openid connect, my purpose is to setup a auth server for my SPA

how do i init the logout flow? 

should i call token/revocation or redirect to session/end to clear the session

as my test token/revocation will clear the token only, user can re-login without typein pwd

session/end is totally destroy the session, which user require to login, but also needed to accept the grant

What i want is make user logout and he/she need to retype the pwd again, but i dont want them to click the grant scope button again

Actually, i really wanna skip the grant flow, and this is the reason i choose openid connect instead of OAUTH2

here is my client config
`clients: [
    {
      client_id: 'test_app',
      client_secret: '123',
      grant_types: ['refresh_token', 'authorization_code'],
      redirect_uris: ['http://localhost:4000/oauth/callback'],
      token_endpoint_auth_method: "none",
      response_types: ['code'],
      application_type: 'web',
      code_challenge:"E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"
    }
  ],`

**Comment by panva** [comment]
> how do i init the logout flow?

https://openid.net/specs/openid-connect-session-1_0-28.html#RPLogout

> should i call token/revocation or redirect to session/end to clear the session

depends on the version of the provider you're using (v5 and v6 have differences), this detail is missing from your issue and i would love it you followed the issue templates and provided useful details in the first place.

> What is the major different between session/end and token/revocation

- https://openid.net/specs/openid-connect-session-1_0-28.html#RPLogout
- https://tools.ietf.org/html/rfc7009

Logout gives the user the opportunity to terminate the OP session, revocation is for revoking OP-issued tokens, nothing will be done with the OP session itself.

> What i want is make user logout and he/she need to retype the pwd again, but i dont want them to click the grant scope button again
> Actually, i really wanna skip the grant flow, and this is the reason i choose openid connect instead of OAUTH2

see https://github.com/panva/node-oidc-provider/blob/v6.5.0/docs/README.md#interactions and the expandable detail https://github.com/panva/node-oidc-provider/blob/v6.5.0/docs/README.md#user-content-interactions-policy-disabling-default-checks

You're going to have to remove the "consent" prompt's checks and replace them with your own that either load pre-existing grants from a DB or completely skip it (not recommended) and call the necessary functions that would be called otherwise (see the expand).
