### ISSUE TITLE
Clients via mongodb

### ISSUE THREAD

**Issue by dobby5** [panva/node-oidc-provider#543]
Hello,

i have been trying for days to retrieve client information via a database (MongoDB). But without success.

The Mongodb adapter is included and I tried different methods.

**Comment by CallMeLaNN** [comment]
Client metadata is statically defined in `clients` configuration but for dynamic clients, you have to turn on `features.registration` to enable OIDC "Dynamic Client Registration" and follow the spec to register new client at `/reg`

**Comment by panva** [comment]
@CallMeLaNN that’s not entirely true. Clients, when not found in the static configuration are also using an adapter to load the metadata. 

@dobby5 you’re going to be more specific with your question. 

The adapter method find(id) is used to retrieve metadata (the same metadata object and types you otherwise configure statically)
