### ISSUE TITLE
Not require mandatory params when using request_uri or request in /auth

### ISSUE THREAD

**Issue by joolfe** [panva/node-oidc-provider#577]
**Describe the bug**
When use request_uri in the '/auth' endpoint without any additional param is not returning an error.
 

**To Reproduce**
I have a create a repo with some test that reproduce the error here 'https://github.com/joolfe/node-oidc-provider-issues'

Steps to reproduce the behaviour:

1.  Download the example code from 'https://github.com/joolfe/node-oidc-provider-issues'
2.  execute `npm install`
3.  execute test using `npm run test-requiredOAuthParams`

**Expected behaviour**
As described in openid section https://openid.net/specs/openid-connect-core-1_0.html#RequestUriParameter

> So that the request is a valid OAuth 2.0 Authorization Request, values for the response_type and client_id parameters MUST be included using the OAuth 2.0 request syntax, since they are REQUIRED by OAuth 2.0. The values for these parameters MUST match those in the Request Object, if present.
Even if a scope parameter is present in the referenced Request Object, a scope parameter MUST always be passed using the OAuth 2.0 request syntax containing the openid scope value to indicate to the underlying OAuth 2.0 logic that this is an OpenID Connect request.

The parameters "client_id", "response_type" and "scope" should be sent as query params to the '/auth' even if a request_uri is pointing to a request object that alreayd have this values, so the oidc provider should validate this and return error if one of this fields is missing as query string or the value not match the value in the request object.

**Environment:**
 - oidc-provider version: v6.14.2
 - node version: v12.13.0
 - npm version: 6.12.0

**Comment by panva** [comment]
Hi @joolfe,

1) you're using [PAR](https://tools.ietf.org/html/draft-lodderstedt-oauth-par-01#section-4) in your example.

> Clients are encouraged to use the request URI as the only parameter in order to use the integrity and authenticity provided by the pushed authorization request.

oidc-provider's PAR implementation uses a unique `urn:` scheme that allows it to process the request without any other parameters. For regular request_uri use (client-hosted) you still need to provide at least the client_id parameter.

2) OIDC's Request Object by Reference is superseded by [JAR](https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-20) which does not have this language

3) the only purpose for this language is allowing existing oauth2 servers be retrofitted with request object references without having to update their "request validation" pipelines too much.

As such, this isn't needed for oidc-provider because it's handling all cases properly, the following is still asserted for the `lax` and `whitelist` merging strategies.

> The values for these parameters MUST match those in the Request Object, if present.

This is still checked.

> Even if a scope parameter is present in the referenced Request Object, a scope parameter MUST always be passed using the OAuth 2.0 request syntax containing the openid scope value to indicate to the underlying OAuth 2.0 logic that this is an OpenID Connect request.

This also doesn't apply anymore since oidc-provider is able to process non-openid requests.

**Comment by joolfe** [comment]
thanks! totally agree with your arguments.
