### ISSUE TITLE
Question: Protected Dynamic Client Registratrion Initial Access Token

### ISSUE THREAD

**Issue by ofairfoul** [panva/node-oidc-provider#578]
Hi @panva I was wondering if you could help me and hopefully others to understand a bit better how to use Dynamic Client Registration and InitialAccessToken correctly. From my understanding of OIDC spec the initial token should be obtained by using Client Credentials or Implicit Grant when not allowing open registration. And this usually would include a scope specific for DCR. And if the initial token was obtained with Implicit Grant then the dynamic client would be bound to the authenticated user.
 
Unfortunately I feel the documentation is a little lacking here in how this should be configured in the provider and there is no example of DCR in the example project. Also it is not clear in which handler the InitialAccessToken should be created. Please could you help?

By the way this is an amazing library. Thanks.

**Comment by panva** [comment]
> From my understanding of OIDC spec the initial token should be obtained by using Client Credentials or Implicit Grant when not allowing open registration. And this usually would include a scope specific for DCR. And if the initial token was obtained with Implicit Grant then the dynamic client would be bound to the authenticated user.

Please enlighten me on this ... can you link the spec sections?

**Comment by ofairfoul** [comment]
Thanks for the quick reply @panva 

Some links as requested:
https://tools.ietf.org/html/rfc7591#section-3.1
> Note that the initial access token sent in
   this example as an OAuth 2.0 Bearer Token [RFC6750], but any OAuth
   2.0 token type could be used by an authorization server.

https://tools.ietf.org/html/rfc7591#appendix-A.1.2
>  While the method by which a client or developer receives
   this initial access token and the method by which the authorization
   server validates this initial access token are out of scope for this
   specification, a common approach is for the developer to use a manual
   preregistration portal at the authorization server that issues an
   initial access token to the developer.

Upon close inspection the spec is not that specific about how it should be used. Each Authorization Server seems to have its own implementation.
[Curity](https://curity.io/resources/architect/openid-connect/openid-connect-understanding-dcr/#architectural-overview-of-dynamic-client-registration) uses client credentials or implicit grant. This is probably where I got my information from but I guess this is implementation specific.

[KeyCloak](https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/client-registration.adoc#authentication) Is a bit more flexible and supports:
- Bearer token for a service account - presumably obtained through client credentials
- Initial Access Token created through a console

Is "initial access token created through a console" the way you envisaged this library being used?

**Comment by panva** [comment]
> Is "initial access token created through a console" the way you envisaged this library being used?

Definitely not. Aside of Initial Access Tokens backed by an adapter you also have the possibility to plug in and require the `software_statement` (see the expandable details [here](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#extraclientmetadata), would need some adaption to accomodate policy), such software statement can be again retrieved through various places that can be backed by either an access token (return from either flow).

Furthermore, the fact that an adapter is aware of the model its looking up, you can very easily lookup an AccessToken or ClientCredential model instead of InitialAccessToken and validate the scope or other claims you assume are present in the object.

Just make sure to change the `kind` property to "InitialAccessToken" before returning it from the adapter, else the provider will assume a mixup. It would also probably make sense to remove the document when it gets used for registering a new client.
