### ISSUE TITLE
Session client authentications

### ISSUE THREAD

**Issue by debben** [panva/node-oidc-provider#60]
I noticed [this TODO block in interactions.js](https://github.com/panva/node-oidc-provider/blob/00c3b21e5464ec983b5141b4f9a92139ccf2ea10/lib/actions/authorization/interactions.js#L130)

```
      // client not authorized in session yet
      // TODO: strategies
      // - authorize once per session
      // - pass everyone
      // - check account model
      () => {
        if (!ctx.session.sidFor(ctx.client.clientId)) {
```

@panva, could you please elaborate on the planned behavior for session authorizations? I have been using oidc-provider with a few RPs that are different but still related. Having no OP session and being prompted by the first RP, my users would expect to have a session that allows them not to be prompted for the other RPs. I'm interested in adding this as a feature. But I wonder though if what you have planned for session authorizations might meet this need.

**Comment by panva** [comment]
Happy to elaborate.

I do not plan to drop the default behavior of one per browser session every RP needs to go to interaction. So once per session is the current, default state.

In early builds a newly encountered RP didn't go to interactions at all, that would be the strategy 'pass everyone'. It's bad for several reasons, so a way in between must be found.

'check account model' or smth similar to it would probably be what you're after, in one of my projects we also have multiple RPs per product and the stakeholders would expect no need to reauthorize... However, the need to reauthorize is there not only for the server, but mainly for the user. You should know that holding back on tokens on a new device is crucial for not having your client abused by malicious mobile software. It also gives you great potential to trigger any tracking or similar functionality for a new device which you otherwise won't have.

What i'm trying to say is that it can be spun as a benefit for both the user and the IdP to have this functionality in place.

Now if you absolutely must have it, i think there's a pretty neat way of achieving it by iterating over your client_ids that should be allowed in, in one of the emitted events that you can register listeners for.

I didn't test this myself but i think something like this should do the trick to pass this interaction check on other clients in this session down the road. Should 'authorization.success' be too late 'interaction.ended' is also a good candidate.
```js
provider.on('authorization.success', function (ctx) {
  const sid = ctx.oidc.session.sidFor(ctx.oidc.params.client_id); // retrieve the existing sid for the client, or generate a new one if you want.
  const anotherClientId = '123'; // or iterate over the related client_ids
  ctx.oidc.session.sidFor(anotherClientId, sid); // set the sid for the other clients like this.
});
```

**Comment by panva** [comment]
I also wonder if there couldn't be a built in way to do this that would revolve around pre-authorization the whole client's sector (sector_identifier_uri client metadata) that's also used for generating the same pairwise identifiers

**Comment by panva** [comment]
now released.

**Comment by debben** [comment]
Thanks!
