### ISSUE TITLE
Logout, then choose "No", still logged out.

### ISSUE THREAD

**Issue by jim-king-2000** [panva/node-oidc-provider#617]
**Describe the bug**

Open the oidc client sample [here](https://tranquil-reef-95185.herokuapp.com/client), login then logout, but choose "No, stay signed in". See it is signed out.

**To Reproduce**
Steps to reproduce the behaviour:

1.  Open "https://tranquil-reef-95185.herokuapp.com/client" in browser.
2.  Create any client, and click "login".
3.  Click "logout" and choose "No, stay signed in".
4.  See it is signed out.

**Expected behaviour**
It should stay signed in.

**Environment:**
 - oidc-provider version: [e.g. v6.17.6]
 - node version: [e.g. v13.3.0]

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
Please read the prompts and implemented behaviours carefully. You are choosing to keep the end user session on the OP by clicking “no”. The RP session is already dropped by the RP and the OP merely removes records of that particular RP visit from the session, but it keeps the user signed as prove. By subsequent authorizations not requiring authentication.

**Comment by jim-king-2000** [comment]
I'm quite new to OIDC. The difference is too trivial to a newbie. Is it possible to remove the prompt (which means always choose "yes")?

**Comment by panva** [comment]
Presenting a prompt for the end user is RECOMMENDED by the specifications.

1) you can customize the logout source to only show the one button you want if you find the functionality isn't needed for your deployment by providing the `logoutPrompt` configuration which you should be providing to style it anyway
2) you can skip the entire prompt or better selectively skip it once you understand the reasons behind it on certain condition (e.g. the id token hint is for the existing session and end-user and is not expired) by providing the `logoutPrompt` configuration which you should be providing to style it anyway and instead of returning an html with the form, include form and automatically submit it via javascript.

**Comment by jim-king-2000** [comment]
Got it. Thanks.
