### ISSUE TITLE
Allow clients to configure 'long' cookie parameters

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#640]
**Is your feature request related to a problem? Please describe.**

When working with native clients (e.g. mobile apps), the 'long' session cookie is problematic for situations where you don't want to launch a browser instance to end the session.

Here is the scenario I'd like to support:

- Web-based clients which use long cookie session and end_session endpoint as normal
- Native mobile app clients which use a library such as AppAuth to authenticate a user and receive access/refresh token for use in subsequent API calls
  - User wishes to log out
  - Native app clears access & refresh tokens locally, and revokes tokens by POSTing to the token revocation endpoint (crucially, no browser session is necessary here, improving the user experience)

Libraries such as AppAuth allow integration with node-oidc-provider by supplying an external user agent that can be launched within the app (i.e. without switching to an external browser). One example is the `ASWebAuthenticationSession` iOS API. Prior to iOS 13, we are unable to control the storage of the cookies in the browser instance, meaning that to support the use case above, the following OIDC configuration settings are necessary:

- long cookie: `maxAge: 1000` (1s - cannot set to '0' or 'null' as this sets a 'transient' cookie, which unfortunately persists until the app quits)
- `expiresWithSession: () { return false; }`

Sadly, the long cookie config is global, and so this effectively disables long sessions for both web and native clients.

**Describe the solution you'd like**

Allow the 'long' cookie settings to be configurable on a client-by-client basis, and allow 'long' cookies to be completely disabled.

**Describe alternatives you've considered**

I'm working around using the configuration above, but this affects web clients, meaning I'll need to keep track of tokens in another set of cookies.

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

I have found other questions relating to the global disabling of long cookies, but nothing exactly as described here. I do feel that for native apps, the ability to disable long cookies would be beneficial for cases where a browser session is _only_ used for the initial authentication.

**Comment by panva** [comment]
I do agree that a more granular control on a library and API level over the cookie TTLs would be great. That being said i don't have any concrete plans to work on this now. I'll ponder on it for a bit and when starting it i'll ping you for feedback.

Please note that if you or your company were to [support](https://github.com/panva/node-oidc-provider?sponsor=1) the library I'd be happy to prioritize sponsored work over other features i have on my mind.

As a workaround until a native solution is offered, you can easily handle this via inspecting the upsert adapter payload and shorten the TTL (or not even store the session) on your adapter level. The only sideeffect is that the cookie will linger around, but since its only a reference, there's no harm in that.

I'm moving this to my backlog for now.

**Comment by fiznool** [comment]
Thank you @panva for your detailed reply. I will investigate the adapter idea, that's not something I had considered.

I appreciate the time you are taking to provide answers like this so quickly. Open source is such a force for good, and figureheads such as yourselves make my job and that of others so much easier. I will reach out to my client and see if there is any support we can provide.

**Comment by slavab89** [comment]
So this is actually something that we're doing. We've changed the session adapter to set a different session expiration time in the DB. Yes, that causes the cookie to stay on the browser for no apparent reason but I don't think it a big issue since the next time the user will try to access the OP he'll get an updated cookie.

In addition to the "configurable" session TTL, we can use the toke TTL function. Basically, there is no reason to have an access token that has a greater lifespan of the session itself (Correct me if I'm wrong here)
