### ISSUE TITLE
Error with dependencies

### ISSUE THREAD

**Issue by thomasvargiu** [panva/node-oidc-provider#646]
Hello! I was updating my project and I have some errors:

```
node_modules/oidc-provider/types/index.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/app/node_modules/oidc-provider/node_modules/@types/node/ts3.2/index.d.ts' and '/app/node_modules/@types/node/ts3.5/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.
```

Why types dependencies are in `dependencies` and not in `devDependencies`?

https://github.com/panva/node-oidc-provider/blob/4f95a708ef6ed3c1d08d9d3aca92d33f9f1be3de/package.json#L51-L52

**Comment by panva** [comment]
@thomasvargiu 

> Why types dependencies are in `dependencies` and not in `devDependencies`?

Some TS developers want them part of the dependencies, some don't. What would you have me do?

**Comment by thomasvargiu** [comment]
I didn't know why types should be in `dependencies`. Looking at [this Stack Overloflow question](https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies) and [this conversation](https://github.com/mui-org/material-ui/issues/14508) I think that `@types/koa` can be in `dependencies` but probably it should be better to exclude `@types/node`.

Let me know what you think.

**Comment by panva** [comment]
Please reach out to the other typescript users from the other typescript threads asking about this. I'm happy to make that change if there's consensus.

If i don't hear back i'ma do it anyway because it kinda makes sense to me, but its better to have consensus.

**Comment by thomasvargiu** [comment]
I agree, but I didn't find a conversation about this. I saw that node definitions are in `dependencies` since the first release where you added the typescript definitions.

**Comment by panva** [comment]
@alvis @thecopy @ajmas @ulrikstrid @fiznool @javlund

Thoughts on the comment [above](https://github.com/panva/node-oidc-provider/issues/646#issuecomment-584272559) and this issue in general?

**Comment by ajmas** [comment]
@types/* should be in devDependencies, but would need to see if there a right way to make it available to downstream during dev time.

Maybe something here: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by fiznool** [comment]
Looking at the `index.d.ts` file, I’d agree with the comment above.
 
- `@types/node` should be in devDependencies, since it is inferred via a tripe-slash reference, rather than directly imported. This is pretty commonplace amongst types - a typescript project would generally always specify its own (dev) dependency on `@types/node`, according to the version of node that they are using (subject of course to the minimum requirements as specified by the library). 

- `@types/koa` should be in dependencies, since it is directly imported in `index.d.ts` and therefore is a requirement for the project to run in development. (Ideally I guess you’d have something that allows you to declare development-only dependencies that are installed alongside the library or module, but AFAIK such a thing does not exist so we need to use dependencies and accept that this will result in an unused dependency in production).

**Comment by panva** [comment]
Moving `@types/node` to devDependencies i get that exact error in CI's lint now. TS is infuriating me yet again, this "awesome types ecosystem" can't decide how to handle requiring its own types, @types/koa requires @types/node as a dependency.

What's a library developer to do when its own regular runtime dependencies require types and they're conflicting with my library users... Infuriating.

**Comment by fiznool** [comment]
One thing I've also seen in the wild is library authors using a more relaxed semver range for the types, so for example here the dependency on node typings could be

``` json
{
  "@types/node": ">=12"
}
```

Would this help to solve the problem?
