### ISSUE TITLE
Access token, interations and sessions saved to db

### ISSUE THREAD

**Issue by tmedanovic** [panva/node-oidc-provider#648]
My introspection, session management and revocation features are disabled but for some reason OIDC provider saves access tokens, sessions and interactions to database.

I understand why grants are saved to Db but I don't see any reason to store things I mentioned above? Can you give me some insight?

Why is this necessary and can it be turned off?

![image](https://user-images.githubusercontent.com/5676600/74628392-eb4d4080-5155-11ea-8e74-b651cda2b0bc.png)

**Comment by panva** [comment]
`introspection`, `sessionManagement` or `revocation` features aren't the trigger to start storing anything extra.

Interactions are the end-user login/consent requests. Access Tokens from the authorization point of view aren't stateless (even if they're JWTs), they get stored so that entire chains of tokens can be revoked when anomalies (double auth code use) or regular flows (refresh token revocation) happens. Sessions are stored so that, well, a user stays logged in?

> Why is this necessary and can it be turned off?

It is and no.

FWIW all records have an expiration and from the looks of it, your use of Dynamo should be configured to take advantage of automated TTL to drop expired records.

**Comment by tmedanovic** [comment]
Well, I don't use auth code or refresh tokens, and since I'm validating access tokens using JWKS I really don't see any benefit to storing access tokens in database, since even if I revoke it - it is still valid.

So signed cookie is not enough to determine if the user is logged in? (Sorry if I'm missing fundementals)?

**Comment by panva** [comment]
So you're using `id_token token` flow? That's unfortunate, since that flow has so many issues that it's actually getting deprecated by upcoming [oauth security topics](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-14#section-2.1.2)

> I'm validating access tokens using

You may be, the provider doesn't, so when a userinfo request is made, it checks its records. If you don't have use for this, just don't store them, i mean, you own the adapter, resolve the upsert without storing it...

The cookies only hold references to DB session objects. Again, it's the more secure way of doing things.

> Sorry if I'm missing fundementals

no worries.
