### ISSUE TITLE
Allow custom token formats/serialisations

### ISSUE THREAD

**Issue by stekycz** [panva/node-oidc-provider#653]
## Is your feature request related to a problem? Please describe.
I want to make sure that any user who has access to the DB of tokens is not able to recreate a valid token from the data saved in the storage. We have created a custom format used in older versions that is not possible to use after the latest major update.

The format has 3 parts:
1. JTI (as it is generated in the library, the value used in `opaque` format)
2. checksum value that is NOT saved in the storage, however, is included for signature calculation and send to the client
3. signature (saved in the storage)

Let's assume the string format is as `<JTI><checksum><signature>` assuming the JTI and checksum always has the same length. However, the serialization to string is another discussion.

The valid token cannot be created without the knowledge or randomly generated checksum value that is sent to the client only.

## Describe the solution you'd like
I would like to be able to configure or/and implement the custom format. It means the following methods:
- `generateTokenId`
- `getValueAndPayload`
- `getTokenId`
- `verify`

I would expect the package to export the TypeScript interface to conform to so I am able to define my custom format.

I also suggest that adding some `matchesFormat(token: string)` method should be added to the interface to support dynamic detection of the format used in the `dynamic` format.

## Describe alternatives you've considered
I am able to do the most of it in the adapter itself (generating checksum value, creating the signature, saving payload without checksum value). However, I am not able to change the value that is considered as the token value that should be sent to the client.

So maybe it might help to allow returning an alternative value from the adapter `upsert` method that would be used when returned instead of the value returned from the `getValueAndPayload`. I would be able to reuse the `opaque` format then.

However, the solution with custom format implementation seems much better to me.

## Additional context
I know that using standard formats provided by the library has its benefits, however, I believe it is better to make the security at the data layer the best possible. Instead of depending on "it will not happen", "the problem of leaking the database is bad as itself" or "if developers take advantage of using DB data then you can sue them". These constraints are too weak.

**Comment by panva** [comment]
Ahoj Martine,

v6.0.0 and onwards does not support overloading the token formats as the previous version did. The methods you're mentioning are now private and used slightly differently.

This is because maintaining that "API" has hindered maintenance and further development of internal formats as it was a dirty practice made public in the first place.

I'm afraid that without a decent amount of refactoring and then some dirty practices applied this won't be possible.

I will consider an entirely new API for registering formats and their subsequent use tho. It's now part of my backlog.

You seem to be a long time user of the library so please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company. Supporting the library means, amongst other things, that your feature request will get a priority when deciding what to work on next.

**Comment by stekycz** [comment]
Thanks! The project it is used in is unfortunately in maintenance only phase 😞We decided to use opaque without the feature we wanted. It is still secure enough and if the package will introduce the new API you are mentioning we will probably use it.

I will pass the sponsoring to the product owner. And I hope we will support you 😉
