### ISSUE TITLE
Track the full consent trip

### ISSUE THREAD

**Issue by victorherraiz-santander** [panva/node-oidc-provider#658]
I am looking for a simple way to track a full trip from push auth request to token endpoint. At the moment is quite dificult to match and correlate all the steps in a single journey. This is required for audit and debug, at the moment we are doing something really dodgy (e.i. request_uri -> interaction_id -> grant_id...)

I would like to have an Identifiar, if it is not current available, to correlate every consent step

**Comment by panva** [comment]
iirc interaction ids are now always equal to the grant id, for PAR, i'll consider to store the uid of the PAR request and use that for the auth request in a future revision.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company. Supporting the library means, amongst other things, that your feature request will get a priority when deciding what to work on next.

**Comment by victorherraiz-santander** [comment]
Iteraction Id are not equal to grandId in version 6.21.1 (we just merge the last tag)

**Comment by panva** [comment]
You're right. I just checked myself. In any case, i've added this to the backlog.

**Comment by panva** [comment]
You're right. I just checked myself. In any case, i've added this to the backlog.

**Comment by panva** [comment]
@victorherraiz-santander 

As a short term quick solution `51b128d` exposes the `Interaction` and `Session` entities on a `ctx.oidc.entities` object.

This will aid you because you can now tie in more entities together in the listeners for events such as `interaction.started` and `authorization.success`. Please note that `PushedAuthorizationRequest` is only present on those on the first load of the PAR object.
