### ISSUE TITLE
Session never expires

### ISSUE THREAD

**Issue by tmedanovic** [panva/node-oidc-provider#668]
We are using implicit flow with response types ` id_token token` and we are using **silent refresh** to rotate tokens during user session.

The long cookie is set to:

      long: { signed: true, path: '/', maxAge: 3600000 }, // 1 hour in ms

However, the session with OIDC never expires and user keeps rotating tokens until he explictly logs out. 

How can I limit the session with OIDC to 1h and still allow sileting refresh every 15min inside the 1h timeframe?

**Comment by panva** [comment]
@tmedanovic the session refreshes its TTL whenever it is used in a request. If you want to limit sessions to 1 hour, do so using your Session dedicated adapter.

**Comment by tmedanovic** [comment]
Thanks.

Ok, and the long cookie is overwritten with new export time? In my case it would be on silent refresh?

The behaviour seems little odd to me because IMO it's common that you want to expire session after some time Wouldn't it be better to add some kind of flag to settings in which you can control whether the cookie gets refreshed after a maxAge?

If we just let the cookie expire, session would be auto deleted because of TTL in DB.
Does that make any sense to you?

**Comment by panva** [comment]
> Ok, and the long cookie is overwritten with new export time? In my case it would be on silent refresh?

Yes, because the user "resurfaced".

> The behaviour seems little odd to me because IMO it's common that you want to expire session after some time

As evidenced by this being the first occurence in 5 years of this project, no, its not common. The most common scenario is that developers want to keep the user session active for as long as possible, not to have the users re-authenticate all the time.

> Wouldn't it be better to add some kind of flag to settings in which you can control whether the cookie gets refreshed after a maxAge?

I don't think we need a flag, as i said, you can orchestrate sessions having a hard TTL regardless of their resurfacing on your adapter layer. When a session is not found in the DB, the cookie can still be in the browser jar but when the user resurfaces its treated as if there was none - user is in a logged out state.

**Comment by tmedanovic** [comment]
Thank you for detailed explanation. Well, in financial applications - it is a common use case. Do you stay logged in at you online banking web application for days?

**Comment by panva** [comment]
In financial application i would never accept the use of deprecated `id_token token` flow in the first place, neither would i support any form iframed silent refresh.

**Comment by tmedanovic** [comment]
@panva Yes, you are right. this is POC. But still a valid use case.
