### ISSUE TITLE
Multi-factor Authentication

### ISSUE THREAD

**Issue by ComputerWolf** [panva/node-oidc-provider#679]
I know there are multiple issues surrounding multi-factor and two factor auth, but none seem to document the proper flow and I am not sure I am doing this properly.

I am attempting to show a screen requesting a code after the username/password screen.

At first I attempted to make the multi-factor code request a Prompt that would fire after the login Prompt, however, I saw that @panva stated that you shouldn't resolve the login interaction until _after_ MFA has been resolved, so this direction would no longer work.

That leads me to either render the multi-factor input screen during the login interaction using `res.render` OR redirect to an MFA endpoint during the login interaction. Either way I seem to not have a great way of retrieving the account information once I need to call `interactionFinished`. Is there a way to put the accountId into the session during the login step and then retrieve it after the multi-factor step? It seems `session` is undefined until `interactionFinished` is called at least once, which doesn't happen in either scenario. What is the best way to go about this?

**Comment by panva** [comment]
I wrote a rant. I deleted it. I wrote it again. Realized you're not to be mad at, it's my shitty documentation and examples. So I deleted it.

Interactions are your land, you control them 100% - their location, when they're requested, when they're resolved, what web framework they use, what middlewares you use in them.

If you're happy with your separate MFA approach, that's fine - i stated that they should be resolved after login because people think of the MFA step as part of login, not as a contextual, potentially optional, step up authentication. If mfa is to be sometimes resolved after authentication, then a separate prompt makes 1000% sense.

Now if you need contextual information in two interaction steps of yours, just add your own session middleware contained in those two routes.
