### ISSUE TITLE
Enable the use of HSM for cryptography

### ISSUE THREAD

**Issue by g4vroche** [panva/node-oidc-provider#681]
**Is your feature request related to a problem? Please describe.**

In order to implement a high or substantial level authentication in the sense of eIDAS regulation, [we need to use "qualified electronic signature creation device"]( https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32015R1502#d1e1055-10-1), in our specific case (french regulation), the device has to be a physical device, a Hardware Security Module (HSM).

We need to use this device to:
 - sign the JWT
 - encrypt keys (private key not going out of the HSM, that's the point)

In the actual state of the code, this process is implemented with JOSE. 

Neither node-oidc-provider nor JOSE provide a way to interface with an HSM rather than using native node crypto, and I believe JOSE won't move in this direction seeing [this recent issue](https://github.com/panva/jose/issues/66).

**Describe the solution you'd like**

Ability to pass cryptographic handlers for various operations (as we have renderError for example)

**Describe alternatives you've considered**

 - Overriding native crypto module prototype 
   => seems really invasive / dangerous

 - configure node-oidc-provider to use plain JWT, and do the crypto outside of the lib ([thanks to middlewares](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#pre--and-post-middlewares))
   => Makes us re-implement JWS/JWE which does not look like a great idea in general.

**Additional context**

We are willing to work on it / make a PR if this is something you would merge.

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests ~and couldn't find anything related.~ actually found [this issue on JOSE](https://github.com/panva/jose/issues/66)

**Comment by kenjinsama** [comment]
:+1:

**Comment by panva** [comment]
> Ability to pass cryptographic handlers for various operations (as we have renderError for example)

Knowing my own lib i think it's not a major pain to refactor some crypto to be based on a HSM call, but what i know will be a pain is to let the provider do its thing while not having the private keys - its a big disruption in the instantiation process etc. A PR is very unlikely to land.

`jose` will not be supporting HSM because its a node crypto module based package. So unless node's crypto has an API for OpenSSL engines, that's not happening in there, I also won't be opening up the surface for "bring your own crypto" any time soon because of how painful it would be to refactor the available algorithm collection and instantiation process.

@g4vroche HSM for crypto is not in scope for me at the moment to add to the public API surface, but please see your email inbox.
