### ISSUE TITLE
BaseToken extensibility

### ISSUE THREAD

**Issue by debben** [panva/node-oidc-provider#72]
I see that the access token is being stored as a JWT, but is only ever handed out as a token identifier with signature. Right now, I have a service that receives the token and uses the the token introspection endpoint on my OP to get the token details. Are there any plans to add configuration for the access_token format returned from the token endpoint?

**Comment by panva** [comment]
> Are there any plans to add configuration for the access_token format returned from the token endpoint?

Not at this point. The only thing configurable atm is the integrity keystore, which only changes the throughput with which tokens can be generated by the OP and it's length (through appending the signature part).

> Right now, I have a service that receives the token and uses the the token introspection endpoint on my OP to get the token details.

I would always recommend this solution, since a JWT formatted access token does not allow for the token to be revoked and this information therefore cannot be returned to RP before it attempts to use it to access resources.


I originally had the plan to not require any adapter to store the tokens and return JWTs only, i encountered issues with that approach very fast.

1. the metadata that's needed to be stored with the access token can get quite heavy (claims parameter, nonce, acr, amr, pixy, redirect_uri, sid, ...) and the token can easily extend a default web server's url length then
2. claims parameter potentially holds User Information (claims parameter), this means either oidc-provider would have to encrypt it (++ complexity, ++ not readable by the RP anyway) or not support the functionality altogether

After starting to define the adapter interface i just sort of stuck with using JWT to serialize the tokens because it's a format that

1. serializes always the same, which in turn allows the library to "version" the internal entity format without dropping backwards compatibility for existing issued tokens
2. the biggest win, i can sign the tokens, noone can manipulate them, and they include expiration in them, removing the need for a storage adapter to remove expired tokens OOB

It's on my TODO for 2.x to move all internal entities that are stored using the provided adapters to just ONE format, JWT is going to be that format, this will simplify the interface (see the diff between stored tokens and sessions), but again still not a JWT that i would return to a RP.

**Comment by panva** [comment]
#294 introduces the option to have any token returned to an RP as a JWT. Calling for comments and reviews.
