### ISSUE TITLE
Using as a proxy for a hand rolled identity provider

### ISSUE THREAD

**Issue by Stono** [panva/node-oidc-provider#834]
Hi, 
Firstly; thanks for all your work on this module.
Secondly; please feel free to dismiss `node-oidc-provider` as a solution to the problem I describe below if what i'm proposing makes no sense! 

At a high level, we have an extremely old service that accepts a `username` and `password`, and returns a json blob of some profile information.  My goal here was to stand up a simple `express` server with `node-oidc-provider` and be able to hit that with same username and password, have `node-oidc-provider` then proxy that request to the old service as an Identity provider, and then subsequently map that back to a strong JWT response, so we're not implementing all the JWT signing etc in this old app.  Does that make sense?

I'm able to create a really simple `service` -> `service` jwt with the following configuration:

```
    const configuration: Configuration = {
      features: {
        clientCredentials: { enabled: true },
        introspection: { enabled: true }
      },
      clients: [
        {
          client_id: 'foo',
          client_secret: 'bar',
          grant_types: ['client_credentials'],
          redirect_uris: [],
          response_types: []
        }
      ]
    }
```

And then i'm able to request a token and introspect it to get a jwt:
```
    const client = new issuer.Client({
      client_id: 'foo',
      client_secret: 'bar',
      token_endpoint_auth_method: 'client_secret_basic',
      response_types: ['id_token']
    })
    const result = await client.grant({ grant_type: 'client_credentials' })
    if (!result.access_token) {
      throw new Error('no access token returned')
    }
    const introspect = await client.introspect(result.access_token)
    console.log(introspect)
```

gives:
```
{
  active: true,
  client_id: 'foo',
  exp: 1607366649,
  iat: 1607366049,
  iss: 'http://localhost:1337',
  jti: 'mdINA56b1l7quq8xkgtv0GyrRcsXW8xd2W21sjWsdGJ',
  token_type: 'Bearer'
}
```

Which is kind of the behaviour I want, but obviously what i'm really looking for his the `clients` to be dynamic, eg I need to offload that `client_credentials` to the old service - and have the JWT contain a subset of information from that upstream service, like username, email etc.

I've done down all sorts of rabbit holes so any help would be appreciated.

**Comment by panva** [comment]
1) clients can easily be dynamic, that's what the `adapter` configuration is also for. If the `client_secret` is meant to replace the legacy `password` then you'll likely want to overload the `provider.Client.prototype.compareClientSecret` method as well.
2) you can also easily use `extraAccessTokenClaims` configuration to fetch any additional data to put into your issued access token.

You may also replace introspection with actually issuing JWT access tokens too.

Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if you wish to discuss further requirements or otherwise want to gain access to more involved help. Supporting the library means, amongst other things, that the library and such support will be available in the future.

**Comment by Stono** [comment]
@panva I've just (personally) sponsored you.  If I can get a basic implementation working then I will push for further sponsorship with my company.

Please could you reopen this issue now and give me a hand?

I've had a look at your suggestions and i'm unsure how to proceed - I just need an extremely basic adapter and compareClientSecret implementation that would give me access to client_id and client_secret to perform authN against a remote service

**Comment by Stono** [comment]
FYI so far I have gotten to this:

```
    this.provider.Client.prototype.compareClientSecret = function compareClientSecret(
      secret: string
    ) {
      console.log('perform validation here', this.clientId, secret)
      return true
    }
```

And a simple Adapter:
```
export default class UrsAdapter implements Adapter {
  private readonly name: string

  constructor(name: string) {
    this.name = name
  }

  public async upsert(id, payload, expiresIn) {
    console.log('seems required but not sure why?')
  }

  async find(id): Promise<AdapterPayload | undefined | void> {
   // Return arbitrary client with id set
    return {
      client_id: id,
      client_secret: 'unknown',
      grant_types: ['client_credentials'],
      redirect_uris: [],
      response_types: []
    }
  }
```

**Comment by panva** [comment]
> Please could you reopen this issue now and give me a hand?

@Stono If you want to have _me_ to aid solve _your company's_ needs then please have them sponsor the library with an appropriate tier first.

There are example adapters [available](https://github.com/panva/node-oidc-provider/tree/master/example/adapters) as well as a [stub](https://github.com/panva/node-oidc-provider/blob/master/example/my_adapter.js) with description of the expected interface.

What you'll want to do is use a generic adapter that stores and returns data from your database (e.g. the tokens that you want issued), but then has a special case in `find` that checks the adapter instance `name` to eql `Client` in which case it'll be returning your "dynamic client".

A quick tip is also, given that your `urs.authenticate` actually returns the extra claims you want, to store those on the client instance (`this`). Then, in order to ensure these instances are ephemeral, have the returned adapter be randomized on each call, that way the built-in cache will not be able to kick in.

**Comment by Stono** [comment]
@panva why does it matter if it's me, or my company that sponsors you?  I personally sponsored you to seek support via GitHub issue so I'm able to prove out this library as a potential implementation before I present it as an option to my company?   It's 9pm here, I can assure you I'm currently working on my personal time as a side idea trying to prove out an idea.

I appreciate your OSS work and you should be rewarded for it, however you will create an impossible hurdle if you're expecting companies to pay for your top tier sponsorship **before** they can even prove out the product is even the right fit for their use case.

**Comment by panva** [comment]
> I personally sponsored you to seek support via GitHub issue so I'm able to prove out this library as a potential implementation

I'm helping here, aren't i?

**Comment by Stono** [comment]
> @Stono If you want to have me to aid solve your company's needs then please have them sponsor the library with an appropriate tier first.

I was directly addressing this.

Best of luck in your OSS endeavours :)

**Comment by panva** [comment]
Sure, let me know if you want further pointers.

**Comment by panva** [comment]
FWIW [here's](https://gist.github.com/panva/5f321be04d4462224b849e83e1663e0a#file-index-js-L81-L116) all my advise combined, most of it right from my very first comment.
