### ISSUE TITLE
Customise logout page

### ISSUE THREAD

**Issue by darbio** [panva/node-oidc-provider#85]
Is there a way to customise the end session page? At the moment it returns a html form which asks them if they want to logout of the OP - I would like to bypass this and just log them out and return them to the application.

**Comment by panva** [comment]
[Get creative ;)](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L239-L259)

**Comment by darbio** [comment]
Cheers. How would I override that in my OP?

**Comment by panva** [comment]
As with all other [configurations](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md) - property of an object as second argument to your new provider instance

**Comment by darbio** [comment]
👍 Thanks

**Comment by slavab89** [comment]
So in order to "bypass" the form that ask the user if he wants to logout from the OP as well, should i get a little hacky and just do a redirect/POST call on the `logoutSource` function?
I understand that the specification indicates that the user should be asked wether he wants to logout from the OP as well or not. But for my use-case i think its more convenient to logout entirely if the user asks to be logged out (no need to double confirmation).

I've seen there is a backchannel logout as well but this wont clear the cookies that he has on the OP domain or destroy the session (correct?)

**Comment by panva** [comment]
> So in order to "bypass" the form that ask the user if he wants to logout from the OP as well, should i get a little hacky and just do a redirect/POST call on the logoutSource function?

Give it a shot, as you pointed out there's a reason why this prompt is there, if you understand the fallout of not having it, nothing can stop from it ;)

> I've seen there is a backchannel logout as well but this wont clear the cookies that he has on the OP domain or destroy the session (correct?)

Incorrect. http://openid.net/specs/openid-connect-backchannel-1_0.html defines a mechanism for a number of RPs to be **notified** via back-channel about the logout event, it is NOT a RP initiated backend logout.

**Comment by slavab89** [comment]
Having a little hard time figuring this out. The reason i want to do this in the first place is because when you log out of Google or another service, you click on the LogOut button and it just logs your out of all the services without asking you once again if you want to log from the OP (as i assume its hidden).

Because the `logoutSource` function is just called with the this context (and its not a generator or something), i cant stop it from moving forward and finishing the flow of the request. Even tried to do a redirect to my own endpoint but if then i try to do some other POST call for the session_end, it starts a new session

Is this even possible? or do-able somehow?

**Comment by panva** [comment]
> Having a little hard time figuring this out. The reason i want to do this in the first place is because when you log out of Google or another service, you click on the LogOut button and it just logs your out of all the services without asking you once again if you want to log from the OP (as i assume its hidden).

[Google](https://accounts.google.com/.well-known/openid-configuration) does not support RP initiated logout (end_session_endpoint is missing) so i wouldn't use it as a reference. [Session Management 1.0](http://openid.net/specs/openid-connect-session-1_0.html) is what oidc-provider implements.

> Because the logoutSource function is just called with the this context (and its not a generator or something), i cant stop it from moving forward and finishing the flow of the request. Even tried to do a redirect to my own endpoint but if then i try to do some other POST call for the session_end, it starts a new session
> 
> Is this even possible? or do-able somehow?

render a self-submitting form with the same inputs?

**Comment by panva** [comment]
Possibly (not tested)

```js
function logoutSource(form) {
    this.body = `<!DOCTYPE html>
<head>
  <title>Logout</title>
</head>
<body>
  ${form}
  <script>
    var form = document.forms[0];
    var input = document.createElement('input');
    input.type = 'hidden';
    input.name = 'logout';
    input.value = 'yes';

    form.appendChild(input);

    form.submit();
  </script>
</body>
</html>`;
  },

```

**Comment by slavab89** [comment]
Cool. Didnt think about this option.
Is this option safe to use in your opinion?

Tried to find information on how google does their logout, if you say its not RP initiated but didnt find something that explained this.
When i click on my avatar and choose logout, it is not considered RP initiated? Is it some flow that they designed for themselves?

**Comment by panva** [comment]
I would assume it's safe when it was initiated with an id_token_hint and a valid post_logout_redirect_uri.

 So, knowing what my library does, I would do the following (feel free to refactor) to skip the user prompt for logouts coming from websites under your control.

```js
function logoutSource(form) {
    // this => koa context;
    if (this.oidc.params.post_logout_redirect_uri) {
      this.body = `<!DOCTYPE html>
  <head>
    <title>Logout</title>
  </head>
  <body>
    ${form}
    <script>
      var form = document.forms[0];
      var input = document.createElement('input');
      input.type = 'hidden';
      input.name = 'logout';
      input.value = 'yes';

      form.appendChild(input);

      form.submit();
    </script>
  </body>
  </html>`;
    } else {
      this.body = `<!DOCTYPE html>
  <head>
    <title>Logout</title>
  </head>
  <body>
    ${form}
    Do you want to logout from the OP?
    <button type="submit" form="op.logoutForm" name="logout" value="yes">Yes</button>
    <button type="submit" form="op.logoutForm">Please don't!</button>
  </body>
  </html>`;
    }
  }
```

The condition check makes it so that simply redirecting to `/session/end` without valid id_token_hint and post_logout_redirect_uri (i.e. by a random website) does not cause a logout automatically.


> Tried to find information on how google does their logout, if you say its not RP initiated but didnt find something that explained this.
When i click on my avatar and choose logout, it is not considered RP initiated? Is it some flow that they designed for themselves?

Sorry, cannot help you there.
