### ISSUE TITLE
Request context in adapter.find

### ISSUE THREAD

**Issue by tsoukup77** [panva/node-oidc-provider#96]
Hi, 

I am using adapter.find(clientId) method to get info about client.
Basically, the method is calling another service (B) which has information about the client.

In the call to the (B), I need to use the same subdomain, that the user used to call the provider.
How do I get context of the original request from the adapter?

Situation:
1) user calls: https://kremilek.chaloupka.com/oidc/auth?client_id=client1&response_type=code&scope=openid&redirect_uri=https://example.com&nonce=foo&state=af0ifjsldkj
2) the adapter in the provider gets called find('client1'). I need to call service (B) such as https://kremilek.chaloupka.com/clients/client1 - I need to know the 'kremilek' subdomain

**Comment by panva** [comment]
As you can see from the code, this is not possible at the moment. I think it would fit the 'next' 2.0.0 branch, where all helpers (findById included) get ctx as a first parameter. If you want to work on this, 2.0.0 would be the place to do so.

**Comment by tsoukup77** [comment]
Thanks for response.
I saw it in the code. I was trying to "hack" it and find a way how to pass some reference to the context, but haven't succeeded. I just wanted to confirm that I am not missing something.

How far is branch 'next' from being able to used as 'stable'? How far is it from first release?

**Comment by panva** [comment]
I'm probably going to push it back until this is done. Problem is that this needs to go to the models first, then to the adapter. And my rails past self keeps screaming when controller/request details are needed in the model.

Is this the project as #95? Just wondering, since both are mentioning subdomains info being crutial...

**Comment by tsoukup77** [comment]
Yes, it is same project as #95 

So the ctx that is passed to it in 'next' branch does not yet contain the info or shall I try and go for it?

**Comment by panva** [comment]
ad #95) use multiple providers for multiple subdomains, as was my recommendation initially.

`next` does not support it either, i merely pointed out that if it were to be pull requested, that branch would be the way to go ...

I don't want to route the ctx through the models (AccessToken, etc.) just so that they're available in the adapter.
